### PR TITLE
 bugfix:when BranchRollback RPC exception not retry and PhaseOne_Failed clean

### LINKED ISSUE #756: when BranchRollback RPC exception not retry
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

when BranchRollback RPC exception not retry

image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by slievrly**
### Ⅰ. Describe what this PR did

bugfix:when BranchRollback RPC exception not retry

### Ⅱ. Does this pull request fix one issue?
fix #756

### CODE REVIEW

File: server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java [hunk 1]
```diff
@@ -284,18 +289,13 @@ public void doGlobalRollback(GlobalSession globalSession, boolean retrying) thro
...
-                    }
                 }
-
+                throw new TransactionException(ex);
             }
 
         }
         if (globalSession.hasBranch()) {
-            SessionHelper.endRollbackFailed(globalSession);
+            throw new ShouldNeverHappenException("GlobalRollback error,GID:" + globalSession.getTransactionId());
```
Comment (CoffeeLatte007) [inline server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java]: why docommit code is 
`if (globalSession.hasBranch()) {
            LOGGER.info("Global[{}] committing is NOT done.", globalSession.getTransactionId());
            return;
        }`
but doRollback code is {
 if (globalSession.hasBranch()) {
            SessionHelper.endRollbackFailed(globalSession);
}
One has only Info log, and the other has a failed state. Should the commit also fail？

Comment (slievrly) [reply server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java]: now doRollback is throw exx; doGlobalCommit contains asyn commit, so it can have branch.

Comment (CoffeeLatte007) [reply server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java]: if branchSesson status is  BranchStatus.PhaseOne_Failed, It will  throw an exception

**Comment by zhangthen** [comment]
Commits is too many?

File: server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java [hunk 2]
```diff
@@ -284,18 +291,13 @@ public void doGlobalRollback(GlobalSession globalSession, boolean retrying) thro
...
```
Comment (CoffeeLatte007) [inline server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java]: Can't get here

**Comment by CoffeeLatte007** [comment]
LGTM

File: server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java [hunk 3]
```diff
@@ -192,11 +200,7 @@ public void doGlobalCommit(GlobalSession globalSession, boolean retrying) throws
                 LOGGER.info("Exception committing branch {}", branchSession, ex);
```
Comment (xingfudeshi) [inline server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java]: Logger.error，and isErrorEnabled

File: server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java [hunk 4]
```diff
@@ -284,21 +290,12 @@ public void doGlobalRollback(GlobalSession globalSession, boolean retrying) thro
                 LOGGER.info("Exception rollbacking branch " + branchSession, ex);
```
Comment (xingfudeshi) [inline server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java]: logger.error，isErrorEnabled
