### PR TITLE
bugfix: FileTransactionStoreManagerTest failed on wins OS

### LINKED ISSUE #1937: FileTransactionStoreManager is never close so the seataFile could not be delete
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

FileTransactionStoreManagerTest test failure, the reason is that `FileTransactionStoreManager.currRaf` is holding the file and the `currRaf` never close. so when call `seataFile.delete` will return a value `false`.

### Ⅲ. Describe what you expected to happen

FileTransactionStoreManager provider a method to close currRaf, so that the file can be delete success.

### Ⅵ. Environment:

- JDK version : oracle jdk8
- OS : windows 10
- seata: 1.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

fix FileTransactionStoreManagerTest failed on wins OS

### Ⅱ. Does this pull request fix one issue?
fixes #1937

### CODE REVIEW

File: server/src/test/java/io/seata/server/store/file/FileTransactionStoreManagerTest.java [hunk 1]
```diff
@@ -74,6 +78,7 @@ public void testFindTimeoutAndSave() throws Exception {
         File seataFile = Files.newTemporaryFile();
         Method findTimeoutAndSaveMethod = FileTransactionStoreManager.class.getDeclaredMethod("findTimeoutAndSave");
         findTimeoutAndSaveMethod.setAccessible(true);
+        FileTransactionStoreManager fileTransactionStoreManager = null;
```
Comment (l81893521) [inline server/src/test/java/io/seata/server/store/file/FileTransactionStoreManagerTest.java]: The method of testFindTimeoutAndSave() test failed.
