### PR TITLE
optimize: delay to delete the expired undo log

### LINKED ISSUE #1464: When the seata-server starts, it should takes a delay to delete the expired undo log
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When the seata-server starts, it should takes a delay to delete the expired undo log. when the 
delete the expired undo log schedule run the first，rm channel was not registered.
image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by jsbxyyx**
### Ⅰ. Describe what this PR did
optimize delay to delete the expired undo log

### Ⅱ. Does this pull request fix one issue?

fixes #1464

### CODE REVIEW

File: server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java [hunk 1]
```diff
@@ -459,7 +459,7 @@ public void init() {
             } catch (Exception e) {
                 LOGGER.info("Exception undoLog deleting ... ", e);
             }
-        },0, UNDOLOG_DELETE_PERIOD,TimeUnit.MILLISECONDS);
+        },3 * 60 * 1000, UNDOLOG_DELETE_PERIOD, TimeUnit.MILLISECONDS);
```
Comment (xingfudeshi) [inline server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java]: define a constant.

Comment (jsbxyyx) [reply server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java]: fix done
