### PR TITLE
bugfix:fix wrong proxy of datasource bean

### LINKED ISSUE #2322: 当使用eureka或者nacos的时候，自动代理无法使用
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

首先，我的项目结构是：
springboot+cloud+eureka+mybatisPlus+seata
在项目中集成seata的过程中，使用seata数据源自动代理，导致项目启动失败；

经过反复的尝试与判断，我觉得是：
seata 与 注册中心 （已尝试过：eureka 与 nacos ）会产生jar包冲突，导致启动失败。

### Ⅱ. Describe what happened

SeataDataSourceBeanPostProcessor 这个文件里面的 proxyDataSource 被执行了两次。

可以看下面的启动日志：

### **Auto proxy of [dataSource]**

这个方法被执行两次是不对的（我的项目是单数据源，没有任何其他的代理设置）
怀疑数据源被多次重复代理，才导致后续的报错。

```
2020-02-28 15:16:17.333  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$c150c326] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.5.RELEASE)

2020-02-28 15:16:17.823  INFO 3756 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Loading nacos data, dataId: 'server-demo', group: 'DEFAULT_GROUP', data: user.name=0
user.age=1
2020-02-28 15:16:17.830  WARN 3756 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[server-demo.properties] & group[DEFAULT_GROUP]
2020-02-28 15:16:17.831  INFO 3756 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource {name='NACOS', propertySources=[NacosPropertySource {name='server-demo.properties'}, NacosPropertySource {name='server-demo'}]}
2020-02-28 15:16:17.870  INFO 3756 --- [           main] com.ydsh.demo.DemoApplication            : No active profile set, falling back to default profiles: default
2020-02-28 15:16:18.522  INFO 3756 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=1b04b7e2-c0dc-351d-8e2f-51534c000165
2020-02-28 15:16:18.552  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.seata.spring.boot.autoconfigure.SeataAutoConfiguration' of type [io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$6ef0be85] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.555  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'springApplicationContextProvider' of type [io.seata.spring.boot.autoconfigure.provider.SpringApplicationContextProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.561  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cloud.alibaba.seata-io.seata.spring.boot.autoconfigure.properties.SpringCloudAlibabaConfiguration' of type [io.seata.spring.boot.autoconfigure.properties.SpringCloudAlibabaConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.563  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'seata-io.seata.spring.boot.autoconfigure.properties.SeataProperties' of type [io.seata.spring.boot.autoconfigure.properties.SeataProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.563  INFO 3756 --- [           main] i.s.s.b.a.SeataAutoConfiguration         : Automatically configure Seata
2020-02-28 15:16:18.611  INFO 3756 --- [           main] io.seata.config.FileConfiguration        : The file name of the operation is registry.conf
2020-02-28 15:16:18.643  INFO 3756 --- [           main] i.s.common.loader.EnhancedServiceLoader  : load ExtConfigurationProvider[null] extension by class[io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider]
2020-02-28 15:16:18.648  INFO 3756 --- [           main] io.seata.config.ConfigurationFactory     : load extConfiguration:FileConfiguration$$EnhancerByCGLIB$$862af1eb
2020-02-28 15:16:18.653  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configProperties' of type [io.seata.spring.boot.autoconfigure.properties.registry.ConfigProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.656  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configFileProperties' of type [io.seata.spring.boot.autoconfigure.properties.registry.ConfigFileProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.656  INFO 3756 --- [           main] io.seata.config.FileConfiguration        : The file name of the operation is file.conf
2020-02-28 15:16:18.656  INFO 3756 --- [           main] io.seata.config.ConfigurationFactory     : load extConfiguration:FileConfiguration$$EnhancerByCGLIB$$862af1eb
2020-02-28 15:16:18.661  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'serviceProperties' of type [io.seata.spring.boot.autoconfigure.properties.file.ServiceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.663  INFO 3756 --- [           main] i.s.s.a.GlobalTransactionScanner         : Initializing Global Transaction Clients ... 
2020-02-28 15:16:18.674  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'threadFactoryProperties' of type [io.seata.spring.boot.autoconfigure.properties.file.ThreadFactoryProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.677  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'transportProperties' of type [io.seata.spring.boot.autoconfigure.properties.file.TransportProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.764  INFO 3756 --- [           main] i.s.c.r.netty.AbstractRpcRemotingClient  : RpcClientBootstrap has started
2020-02-28 15:16:18.766  INFO 3756 --- [           main] i.s.s.a.GlobalTransactionScanner         : Transaction Manager Client is initialized. applicationId[applicationName] txServiceGroup[my_test_tx_group]
2020-02-28 15:16:18.783  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'rmProperties' of type [io.seata.spring.boot.autoconfigure.properties.file.RmProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.783  INFO 3756 --- [           main] io.seata.rm.datasource.AsyncWorker       : Async Commit Buffer Limit: 1000
2020-02-28 15:16:18.790  INFO 3756 --- [           main] i.s.c.r.netty.AbstractRpcRemotingClient  : RpcClientBootstrap has started
2020-02-28 15:16:18.790  INFO 3756 --- [           main] i.s.s.a.GlobalTransactionScanner         : Resource Manager is initialized. applicationId[applicationName] txServiceGroup[my_test_tx_group]
2020-02-28 15:16:18.790  INFO 3756 --- [           main] i.s.s.a.GlobalTransactionScanner         : Global Transaction Clients are initialized. 
2020-02-28 15:16:18.853  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$a536c029] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:18.883  INFO 3756 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$c150c326] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-28 15:16:19.119  INFO 3756 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8523 (http)
2020-02-28 15:16:19.141  INFO 3756 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-02-28 15:16:19.141  INFO 3756 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.19]
2020-02-28 15:16:19.283  INFO 3756 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-02-28 15:16:19.283  INFO 3756 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1398 ms
2020-02-28 15:16:19.577  INFO 3756 --- [           main] s.s.a.d.SeataDataSourceBeanPostProcessor : Auto proxy of [scopedTarget.dataSource]
2020-02-28 15:16:19.579  INFO 3756 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-02-28 15:16:19.954  INFO 3756 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2020-02-28 15:16:20.155  INFO 3756 --- [           main] i.s.common.loader.EnhancedServiceLoader  : load DbTypeParser[druid] extension by class[io.seata.sqlparser.druid.DruidDelegatingDbTypeParser]
2020-02-28 15:16:20.177  INFO 3756 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : will connect to 192.168.0.8:8091
2020-02-28 15:16:20.177  INFO 3756 --- [           main] io.seata.core.rpc.netty.RmRpcClient      : RM will register :jdbc:mysql://192.168.0.251/ydsh_bms
2020-02-28 15:16:20.183  INFO 3756 --- [           main] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:RMROLE,address:192.168.0.8:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://192.168.0.251/ydsh_bms', applicationId='applicationName', transactionServiceGroup='my_test_tx_group'} >
2020-02-28 15:16:20.475  INFO 3756 --- [lector_RMROLE_1] i.s.common.loader.EnhancedServiceLoader  : load Serializer[SEATA] extension by class[io.seata.serializer.seata.SeataSerializer]
2020-02-28 15:16:20.499  INFO 3756 --- [           main] io.seata.core.rpc.netty.RmRpcClient      : register RM success. server version:1.1.0,channel:[id: 0xfccadf7b, L:/192.168.0.66:60971 - R:/192.168.0.8:8091]
2020-02-28 15:16:20.508  INFO 3756 --- [           main] i.s.core.rpc.netty.NettyPoolableFactory  : register success, cost 63 ms, version:1.1.0,role:RMROLE,channel:[id: 0xfccadf7b, L:/192.168.0.66:60971 - R:/192.168.0.8:8091]
2020-02-28 15:16:20.569  INFO 3756 --- [           main] s.s.a.d.SeataDataSourceBeanPostProcessor : Auto proxy of [dataSource]
2020-02-28 15:16:20.583  INFO 3756 --- [           main] io.seata.core.rpc.netty.RmRpcClient      : will register resourceId:jdbc:mysql://192.168.0.251/ydsh_bms
2020-02-28 15:16:20.635  WARN 3756 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jopMapper' defined in file [E:\easy-life\elife\saas\saas-core-demo\target\classes\com\ydsh\demo\mapper\JopMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: GlobalConfigUtils setMetaData Fail !  Cause:com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Get proxy targetObject exception !  Cause:java.lang.NoSuchFieldException: advised
2020-02-28 15:16:20.638  INFO 3756 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-02-28 15:16:20.648  INFO 3756 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2020-02-28 15:16:20.649  INFO 3756 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-02-28 15:16:20.660  INFO 3756 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-02-28 15:16:20.672 ERROR 3756 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jopMapper' defined in file [E:\easy-life\elife\saas\saas-core-demo\target\classes\com\ydsh\demo\mapper\JopMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: GlobalConfigUtils setMetaData Fail !  Cause:com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Get proxy targetObject exception !  Cause:java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1515) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:824) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at com.ydsh.demo.DemoApplication.main(DemoApplication.java:22) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: GlobalConfigUtils setMetaData Fail !  Cause:com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Get proxy targetObject exception !  Cause:java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1248) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1168) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1500) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	... 17 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: GlobalConfigUtils setMetaData Fail !  Cause:com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Get proxy targetObject exception !  Cause:java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	... 30 common frames omitted
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: GlobalConfigUtils setMetaData Fail !  Cause:com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Get proxy targetObject exception !  Cause:java.lang.NoSuchFieldException: advised
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:49) ~[mybatis-plus-core-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:483) ~[mybatis-plus-extension-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:433) ~[mybatis-plus-extension-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.getObject(MybatisSqlSessionFactoryBean.java:627) ~[mybatis-plus-extension-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.sqlSessionFactory(MybatisPlusAutoConfiguration.java:197) ~[mybatis-plus-boot-starter-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$e2ff2cc3.CGLIB$sqlSessionFactory$2(<generated>) ~[mybatis-plus-boot-starter-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$e2ff2cc3$$FastClassBySpringCGLIB$$5dec3912.invoke(<generated>) ~[mybatis-plus-boot-starter-3.1.2.jar:3.1.2]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$e2ff2cc3.sqlSessionFactory(<generated>) ~[mybatis-plus-boot-starter-3.1.2.jar:3.1.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	... 31 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:60954', transport: 'socket'

Process finished with exit code 1

```

### Ⅲ. Describe what you expected to happen（The process of sifting through problems）

接着我继续排查，是什么原因导致了 proxyDataSource 被执行了两次。
因为我项目是个很干净的demo，所以我们就开始一个一个包的删掉，来排查问题。
ps：在此非常感谢 吴江坷 大佬帮我排查问题

经过排查：
### **当我把eureka的包删掉的时候，项目奇迹般的正常启动了。（proxyDataSource只被执行了一次。）**
所以我当场就怀疑是 seata 与 eureka 冲突了。这个时候，我果断抛弃了eureka，决定换成 nacos ，投入“阿里爸爸”的怀抱

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1、将seata的jar引入：
2、将eureka或者nacos的jar引入
附上我demo的pom.xml
```
    <dependencies>

        <!-- lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.8</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Spring Boot mybatis-plus 依赖 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- seata-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.0.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.1.0</version>
        </dependency>


        <!--nacos 服务发现-->

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.1.1.RELEASE</version>
        </dependency>


         <!--eureka 服务发现-->

        <!--        <dependency>-->
        <!--            <groupId>org.springframework.cloud</groupId>-->
        <!--            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>-->
        <!--            <version>2.1.5.RELEASE</version>-->
        <!--        </dependency>-->

    </dependencies>

```

### Ⅴ. Anything else we need to know?

使用seata自动代理的时候我的相关配置：
seata.enabled=true
seata.enableAutoDataSourceProxy=true
seata.useJdkProxy=false

在排查的时候，我将seata设置了直连：
seata.service.grouplist.seata-server:192.168.0.8:8091

也就是说，只要项目里面有 eureka 或者 nacos 的jar （无需注册与开启eureka 或者 nacos ），项目启动就会失败，报上面的错误。

真心是存在问题的，很严谨的测试了两三天，希望能得到重视与解决，项目还在等待集成seata呢~~

### Ⅵ. Environment:

- JDK version : 1.8
- OS : seata-server：CentOS7 
- Others: maven：apache-maven-3.5.4

### PR DESCRIPTION
**Pull request by xingfudeshi**
### Ⅰ. Describe what this PR did
fix wrong proxy of datasource bean

### Ⅱ. Does this pull request fix one issue?

fixes #2322 #2311 #2321 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
I've done integration testing.

### CODE REVIEW

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java [hunk 1]
```diff
@@ -105,4 +113,62 @@ private Object handleMethodProxy(DataSourceProxy dataSourceProxy, Method method,
...
+        Object fieldObject = field.get(proxiedObject);
+        return Stream.of(fieldObject.getClass().getDeclaredFields()).anyMatch(f -> {
+            f.setAccessible(true);
+            Object targetObject;
+            try {
+                targetObject = f.get(fieldObject);
+            } catch (IllegalAccessException e) {
+                throw new RuntimeException(e);
+            }
+            return targetObject instanceof DataSourceProxy;
```
Comment (ggndnn) [inline spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: In JDK Proxy case, what invocationHandler has a field of type DataSourceProxy?

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java [hunk 2]
```diff
@@ -105,4 +113,62 @@ private Object handleMethodProxy(DataSourceProxy dataSourceProxy, Method method,
...
+     * @param field
+     * @param proxiedObject
+     * @return
+     * @throws IllegalAccessException
+     */
+    private boolean doCheckAutoProxy(Field field, Object proxiedObject) throws IllegalAccessException {
+        if (null == field) {
+            return false;
+        }
+        field.setAccessible(true);
```
Comment (ggndnn) [inline spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: Need to restore accessible?

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java (hunk 1 above)
Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: When datasource bean has been proxied once.

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java [hunk 3]
```diff
@@ -105,4 +113,62 @@ private Object handleMethodProxy(DataSourceProxy dataSourceProxy, Method method,
...
+     */
+    private boolean isAutoProxiedBySeata(Object bean) throws NoSuchFieldException, IllegalAccessException {
+        if (bean instanceof DataSourceProxy) {
+            return true;
+        }
+        //handle Spring AOP
+        Object proxyTargetObject = bean;
+        if (AopUtils.isAopProxy(proxyTargetObject)) {
+            try {
+                proxyTargetObject = SpringProxyUtils.getAdvisedSupport(bean).getTargetSource().getTarget();
```
Comment (slievrly) [inline spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: only for cglib?

Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: Both of jdk and cglib.

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java [hunk 4]
```diff
@@ -105,4 +113,62 @@ private Object handleMethodProxy(DataSourceProxy dataSourceProxy, Method method,
...
+            }
+        }
+        Field field = null;
+        //handle Normal proxy object
+        if (ClassUtils.isCglibProxy(proxyTargetObject)) {
+            //CGLIB Proxy
+            field = proxyTargetObject.getClass().getDeclaredField("CGLIB$CALLBACK_0");
+        } else if (Proxy.isProxyClass(proxyTargetObject.getClass())) {
+            //JDK Proxy
+            field = proxyTargetObject.getClass().getDeclaredField("h");
```
Comment (slievrly) [inline spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: getClass -> getSuperclass

Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: fixed

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java (hunk 2 above)
Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java]: fixed

**Comment by ggndnn** [comment]
@xingfudeshi 
I think this pr is not a final solution of the issues mentioned above, e.g., the cause of #2321 is that seata used cglib to create a proxy instance whose type was a subclass of `DynamicDataSource`, but it's field `resolvedDataSources` was not initialized, and more importantly, the proxied bean was not repeatedly proxied before.

So here are some advices:
1) To create proxy in spring way when auto proxying running in spring context, some frameworks assume that the proxy class is created in spring way, e.g., mybatis-plus.
2) To provide `include` or `exclude` kind attributes to `@EnableAutoDataSourceProxy` helping users to control auto proxy target.
e.g., @EnableAutoDataSourceProxy(include=HikariDataSource.class, exclude= AbstractRoutingDataSource.class),  something like this.
3) To recursive check duplication auto proxying, though I am not so sure whether this point is necessary.

**Comment by xingfudeshi** [comment]
> @xingfudeshi
> I think this pr is not a final solution of the issues mentioned above, e.g., the cause of #2321 is that seata used cglib to create a proxy instance whose type was a subclass of `DynamicDataSource`, but it's field `resolvedDataSources` was not initialized, and more importantly, the proxied bean was not repeatedly proxied before.
> 
> So here are some advices:
> 
> 1. To create proxy in spring way when auto proxying running in spring context, some frameworks assume that the proxy class is created in spring way, e.g., mybatis-plus.
> 2. To provide `include` or `exclude` kind attributes to `@EnableAutoDataSourceProxy` helping users to control auto proxy target.
>    e.g., @EnableAutoDataSourceProxy(include=HikariDataSource.class, exclude= AbstractRoutingDataSource.class),  something like this.
> 3. To recursive check duplication auto proxying, though I am not so sure whether this point is necessary.

Please review.

File: seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java [hunk 5]
```diff
@@ -47,6 +47,10 @@
      * Whether use JDK proxy instead of CGLIB proxy
      */
     private boolean useJdkProxy = false;
+    /**
+     * Specifies which datasource bean are not eligible for auto-proxying
+     */
+    private String[] excludeForAutoProxying = {};
```
Comment (ggndnn) [inline seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java]: Do we need a include attribute?

File: spring/src/main/java/io/seata/spring/annotation/datasource/EnableAutoDataSourceProxy.java [hunk 6]
```diff
@@ -38,4 +38,10 @@
      * @return useJdkProxy
      */
     boolean useJdkProxy() default false;
+
+    /**
+     * Specifies which datasource bean are not eligible for auto-proxying
+     * @return
+     */
+    String[] exclude() default {};
```
Comment (ggndnn) [inline spring/src/main/java/io/seata/spring/annotation/datasource/EnableAutoDataSourceProxy.java]: Do we need a include attribute?

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+import org.springframework.aop.TargetSource;
+import org.springframework.aop.framework.AdvisedSupport;
+import org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator;
+import org.springframework.aop.support.AopUtils;
+import org.springframework.beans.BeansException;
+
+/**
+ * @author xingfudeshi@gmail.com
+ */
+public class SeataAutoDataSourceProxyCreator extends AbstractAutoProxyCreator {
```
Comment (ggndnn) [inline spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java]: I have an idea, ProxyCreator can be implement like this:
```
// define a mark interface
public interface SeataProxy {
}

// implements MethodInterceptor and IntroductionInfo
public class SeataAutoDataSourceProxyAdvice implements MethodInterceptor, IntroductionInfo {
    private final DataSourceProxy dataSourceProxy;

    public SeataAutoDataSourceProxyAdvice(DataSourceProxy dataSourceProxy) {
        this.dataSourceProxy = dataSourceProxy;
    }
    
    ...

    @Override
    public Class<?>[] getInterfaces() {
        return new Class[]{SeataProxy.class};
    }
}

// extends AbstractAutoProxyCreator
public class SeataAutoDataSourceProxyCreator extends AbstractAutoProxyCreator {
    protected abstract Object[] getAdvicesAndAdvisorsForBean(Class<?> beanClass, String beanName, TargetSource customTargetSource) throws BeansException {
        advice = new SeataAutoDataSourceProxyAdvice()
        // use DefaultIntroductionAdvisor
        advisor = new DefaultIntroductionAdvisor(advice);
        return new Object[]{advisor};
    }
 
    @Override    
    protected boolean shouldSkip(Class<?> beanClass, String beanName) {
        return SeataProxy.class.isAssignableFrom(beanClass) || beanName ....;
    }
}
```

File: spring/src/main/java/io/seata/spring/annotation/datasource/EnableAutoDataSourceProxy.java (hunk 6 above)
Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/EnableAutoDataSourceProxy.java]: I don't think we need the include attribute, and exclude is only to avoid unnecessary proxy. In fact, even if the proxy, it won't have any impact.

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java (hunk 7 above)
Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java]: Good idea!!

File: spring/src/main/java/io/seata/spring/annotation/datasource/EnableAutoDataSourceProxy.java (hunk 6 above)
Comment (ggndnn) [reply spring/src/main/java/io/seata/spring/annotation/datasource/EnableAutoDataSourceProxy.java]: It makes sense. But I think `include` is an effective feature helping users to control auto proxying, avoiding unexpected situations, there is no harm to provide such a function. 
By the way, should `exclude` be `excludes`? Because the attribute is array type.

Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/EnableAutoDataSourceProxy.java]: done

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+    private MethodInterceptor advice;
+    private final String[] excludes;
+
+    public SeataAutoDataSourceProxyCreator(boolean useJdkProxy, String[] excludes) {
+        this.excludes = excludes;
+        setProxyTargetClass(!useJdkProxy);
+    }
+
+    @Override
+    protected Object wrapIfNecessary(Object bean, String beanName, Object cacheKey) {
```
Comment (ggndnn) [inline spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java]: What I thought is to not override `wrapIfNecessary` and fully make use of `AbstractAutoProxyCreator`, something like this:

```
public class SeataAutoDataSourceProxyCreator extends AbstractAutoProxyCreator {
    private final String[] excludes;

    private final DefaultIntroductionAdvisor advisor = new DefaultIntroductionAdvisor(new SeataAutoDataSourceProxyAdvice());

    public SeataAutoDataSourceProxyCreator(boolean useJdkProxy, String[] excludes) {
        this.excludes = excludes;
        setProxyTargetClass(!useJdkProxy);
    }

    @Override
    protected Object[] getAdvicesAndAdvisorsForBean(Class<?> beanClass, String beanName, TargetSource customTargetSource) throws BeansException {
        return new Object[]{advisor};
    }

    @Override
    protected boolean shouldSkip(Class<?> beanClass, String beanName) {
        return SeataProxy.class.isAssignableFrom(beanClass) ||
                !DataSource.class.isAssignableFrom(beanClass) ||
                Arrays.asList(excludes).contains(beanClass.getName());
    }
}

public class SeataAutoDataSourceProxyAdvice implements MethodInterceptor, IntroductionInfo {
    @Override
    public Object invoke(MethodInvocation invocation) throws Throwable {
        DataSource dataSource = (DataSource) invocation.getThis();
        DataSourceProxy dataSourceProxy = DataSourceProxyHolder.get().putDataSource(dataSource);
        Method method = invocation.getMethod();
        Object[] args = invocation.getArguments();
        Method m = BeanUtils.findDeclaredMethod(DataSourceProxy.class, method.getName(), method.getParameterTypes());
        if (null != m) {
            return m.invoke(dataSourceProxy, args);
        } else {
            return invocation.proceed();
        }
    }

    @Override
    public Class<?>[] getInterfaces() {
        return new Class[]{SeataProxy.class};
    }

}
```

File: spring/src/main/java/io/seata/spring/annotation/datasource/AutoDataSourceProxyRegistrar.java [hunk 9]
```diff
@@ -27,16 +27,20 @@
  */
 public class AutoDataSourceProxyRegistrar implements ImportBeanDefinitionRegistrar {
     private static final String ATTRIBUTE_KEY_USE_JDK_PROXY = "useJdkProxy";
-    public static final String BEAN_NAME_SEATA_DATA_SOURCE_BEAN_POST_PROCESSOR = "seataDataSourceBeanPostProcessor";
+    private static final String ATTRIBUTE_KEY_EXCLUDE = "exclude";
```
Comment (ggndnn) [inline spring/src/main/java/io/seata/spring/annotation/datasource/AutoDataSourceProxyRegistrar.java]: excludes?

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java (hunk 8 above)
Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java]: Fixed.Thanks.

File: spring/src/main/java/io/seata/spring/annotation/datasource/AutoDataSourceProxyRegistrar.java (hunk 9 above)
Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/AutoDataSourceProxyRegistrar.java]: Fixed

File: seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java [hunk 10]
```diff
@@ -101,4 +105,13 @@ public SeataProperties setUseJdkProxy(boolean useJdkProxy) {
         this.useJdkProxy = useJdkProxy;
         return this;
     }
+
+    public String[] getExcludesForAutoProxying() {
```
Comment (slievrly) [inline seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java]: ing means doing？

File: spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyAdvice.java [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+    @Override
+    public Object invoke(MethodInvocation invocation) throws Throwable {
+        DataSourceProxy dataSourceProxy = DataSourceProxyHolder.get().putDataSource((DataSource) invocation.getThis());
+        Method method = invocation.getMethod();
+        Object[] args = invocation.getArguments();
+        Method m = BeanUtils.findDeclaredMethod(DataSourceProxy.class, method.getName(), method.getParameterTypes());
+        if (null != m) {
+            return m.invoke(dataSourceProxy, args);
+        } else {
+            return invocation.proceed();
```
Comment (ggndnn) [inline spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyAdvice.java]: Do we need to throw exception or log warning message when m == null?

Comment (xingfudeshi) [reply spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyAdvice.java]: When m=null,the method of original bean should be called.

File: seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java (hunk 10 above)
Comment (xingfudeshi) [reply seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java]: Yes, but sometimes it means gerund.Need to change to proxy?
