### PR TITLE
bugfix : unable to register nacos

### LINKED ISSUE #2586: nacos1.2 开启登录, docker部署seata-server:latest 使用nacos作为注册中心, 启动失败
1. 前置环境
   1) nacos1.2, 宿主机部署, 使用登录  (nacos.core.auth.enabled=true)
   2) docker 部署 seataio/seata-server:latest
2. 使用外部配置文见
  1) 启动命令
     docker run --name seata-server -d --restart always  -e SEATA_CONFIG_NAME=file:/root/seata-config/registry -p 8091:8091 -v $PWD/config:/root/seata-config  seataio/seata-server
  2) 配置文件
    file.conf 使用db  配置数据库
   registry.conf 配置nacos作为注册中心, 配置中心(相关配置已导入  config.txt)
    registry {
      type = "nacos"

      nacos {
        application = "seata-server"
        serverAddr = "127.0.0.1"
        namespace = "server"
        cluster = "default"
        username = "nacos"
       password = "nacos"
    }
  }

config {
  type = "nacos"

  nacos {
    serverAddr = "127.0.0.1"
    namespace = "server"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
}

启动错误信息:
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([127.0.0.1]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Apr 20 15:52:57 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

### PR DESCRIPTION
**Pull request by a364176773**
### Ⅰ. Describe what this PR did
bugfix : unable to register nacos

### Ⅱ. Does this pull request fix one issue?

fix #2586

### CODE REVIEW

File: discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java [hunk 1]
```diff
@@ -235,12 +235,12 @@ private static String getNacosApplicationFileKey() {
     }
 
     private static String getNacosUserName() {
-        return String.join(ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR, ConfigurationKeys.FILE_ROOT_CONFIG, REGISTRY_TYPE,
+        return String.join(ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR, ConfigurationKeys.FILE_ROOT_REGISTRY, REGISTRY_TYPE,
```
Comment (objcoding) [inline discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java:238]: nacos Config center username is useless?

Comment (a364176773) [reply discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java:238]: > nacos Config center username is useless?

there is an error here, the registry value should be read

Comment (objcoding) [reply discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java:238]: ok.
