### PR TITLE
bugfix: fix deadlock and lock optimization

### LINKED ISSUE #1603: MemoryLocker deadlock
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Deadlock happened in `io.seata.server.lock.memory.MemoryLocker`, when two branch transactions of same TM concurrently execute, and branch transaction1(BT1) wanna acquire lock with lockKeys: `table1:1,2,3,4,5`, BT2 wanna acquire lock with lockKeys: `table1:5,4,3,2,1`.

### Ⅱ. Describe what happened
My analysis result is:
In `io.seata.server.lock.memory.MemoryLocker#acquireLock`, it will hold the bucketLockMap's monitor lock then do the acquire lock process, if PK is locked by other transaction, it means lock conflict happened, and then it will release all branch transaction acquired locks. But the point is it release all acquired locks with the bucket monitor lock holding. If two branch transaction acquire locks in a different order, deadlock happen.  

Go back to what i described before, BT1 wanna acquire PK locks `1,2,3,4,5`,BT2 wanna acquire PK locks `5,4,3,2,1`, they execute concurrently:
1. BT1 already gets PK locks `1,2`
2. BT2 already gets PK locks `5,4`
3. BT1 and BT2 both wanna to acquire PK lock `3`, and BT1 actually finish it
3. BT1 wanna to get PK lock `4`, but finds it locked by BT2, then BT1 tries to release PK locks `1,2,3`, at this time BT1 holds the PK lock `4`'s bucket monitor lock
4.  BT2 wanna to get PK lock `3`, but finds it locked by BT1, then BT2 tries to release PK locks `5,4`, at this time BT2 holds the PK lock `3`'s bucket monitor lock
5. BT1 holds `4`'s bucket lock and wanna release `3`(which need `3`'s bucket monitor lock), BT2 holds `3`'s bucket lock and wanna release `4`, deadlock happened
### Ⅲ. Describe what you expected to happen
MemoryLocker could work without deadlock.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. edit `io.seata.server.lock.LockManagerTest`
2. copy function `deadlockBranchSessionsProvider` and function `deadlockTest` to `LockManagerTest`
3. run `deadlockTest`
4. deadlock happened
```java
@ParameterizedTest
@MethodSource("deadlockBranchSessionsProvider")
public void deadlockTest(BranchSession branchSession1, BranchSession branchSession2) throws Exception {
    LockManager lockManager = new MemoryLockManagerForTest();
    final AtomicBoolean first = new AtomicBoolean();
    final AtomicBoolean second = new AtomicBoolean();
    CountDownLatch countDownLatch = new CountDownLatch(2);
    new Thread(() -> {
        try {
            first.set(lockManager.acquireLock(branchSession1));
        } catch (TransactionException e) {
           e.printStackTrace();
        } finally {
            countDownLatch.countDown();
        }
    }).start();
    new Thread(() -> {
        try {
            second.set(lockManager.acquireLock(branchSession2));
        } catch (TransactionException e) {
            e.printStackTrace();
        } finally {
            countDownLatch.countDown();
        }
    }).start();
    countDownLatch.await();
    System.out.println("Result: first is " + first.get() + " ,second is " + second.get());
    Assertions.assertTrue(first.get() || second.get());
}

static Stream<Arguments> deadlockBranchSessionsProvider() {
    BranchSession branchSession1 = new BranchSession();
    branchSession1.setTransactionId(UUIDGenerator.generateUUID());
    branchSession1.setBranchId(1L);
    branchSession1.setClientId("c1");
    branchSession1.setResourceGroupId("my_test_tx_group");
    branchSession1.setResourceId("tb_1");
    branchSession1.setLockKey("t:1,2,3,4,5");
    branchSession1.setBranchType(BranchType.AT);
    branchSession1.setApplicationData("{\"data\":\"test\"}");
    branchSession1.setBranchType(BranchType.AT);

    BranchSession branchSession2 = new BranchSession();
    branchSession2.setTransactionId(UUIDGenerator.generateUUID());
    branchSession2.setBranchId(2L);
    branchSession2.setClientId("c1");
    branchSession2.setResourceGroupId("my_test_tx_group");
    branchSession2.setResourceId("tb_1");
    branchSession2.setLockKey("t:5,4,3,2,1");
    branchSession2.setBranchType(BranchType.AT);
    branchSession2.setApplicationData("{\"data\":\"test\"}");
    branchSession2.setBranchType(BranchType.AT);
    return Stream.of(
            Arguments.of(branchSession1, branchSession2));
}
```
I add some logs in `MemoryLocker`, these logs could prove my analysis:
```
2019-09-06 14:19:58.553 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:96 -Acquire lock process wanna use bucket(1488605238)'s monitor lock, content is: {}, transaction: 1002
2019-09-06 14:19:58.553 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:96 -Acquire lock process wanna use bucket(839131056)'s monitor lock, content is: {}, transaction: 1001
2019-09-06 14:19:58.594 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:134 -Acquire lock process already free bucket(1488605238)'s monitor lock, content is: {5=1002}, transaction: 1002
2019-09-06 14:19:58.594 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:134 -Acquire lock process already free bucket(839131056)'s monitor lock, content is: {1=1001}, transaction: 1001
2019-09-06 14:19:58.594 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:96 -Acquire lock process wanna use bucket(1051681639)'s monitor lock, content is: {}, transaction: 1002
2019-09-06 14:19:58.594 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:96 -Acquire lock process wanna use bucket(2030237312)'s monitor lock, content is: {}, transaction: 1001
2019-09-06 14:19:58.595 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:134 -Acquire lock process already free bucket(2030237312)'s monitor lock, content is: {2=1001}, transaction: 1001
2019-09-06 14:19:58.595 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:134 -Acquire lock process already free bucket(1051681639)'s monitor lock, content is: {4=1002}, transaction: 1002
2019-09-06 14:19:58.595 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:96 -Acquire lock process wanna use bucket(1448018216)'s monitor lock, content is: {}, transaction: 1001
2019-09-06 14:19:58.595 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:96 -Acquire lock process wanna use bucket(1448018216)'s monitor lock, content is: {}, transaction: 1002
2019-09-06 14:19:58.595 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:134 -Acquire lock process already free bucket(1448018216)'s monitor lock, content is: {3=1001}, transaction: 1001
2019-09-06 14:19:58.595 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:115 -Global lock on [t:3] is holding by 1001
2019-09-06 14:19:58.595 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:96 -Acquire lock process wanna use bucket(1051681639)'s monitor lock, content is: {4=1002}, transaction: 1001
2019-09-06 14:19:58.596 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:115 -Global lock on [t:4] is holding by 1002
2019-09-06 14:19:58.610 INFO [Thread-2]io.seata.common.loader.EnhancedServiceLoader.loadFile:237 -load Locker[file] extension by class[io.seata.server.lock.memory.MemoryLocker]
2019-09-06 14:19:58.611 INFO [Thread-2]io.seata.core.lock.AbstractLocker.releaseLock:150 -Release lock process wanna use bucket(1051681639)'s monitor lock, content is: {4=1002}, transaction: 1002
2019-09-06 14:19:58.611 INFO [Thread-1]io.seata.core.lock.AbstractLocker.releaseLock:150 -Release lock process wanna use bucket(839131056)'s monitor lock, content is: {1=1001}, transaction: 1001
2019-09-06 14:19:58.611 INFO [Thread-1]io.seata.core.lock.AbstractLocker.releaseLock:162 -Release lock process already free bucket(839131056)'s monitor lock, content is: {}, transaction: 1001
2019-09-06 14:19:58.611 INFO [Thread-1]io.seata.core.lock.AbstractLocker.releaseLock:150 -Release lock process wanna use bucket(1448018216)'s monitor lock, content is: {3=1001}, transaction: 1001

```
### Ⅴ. Anything else we need to know?
This bug could been resolved by moving the lock release process to the out of bucket monitor lock scope:
```java
// in io.seata.server.lock.memory.MemoryLocker#acquireLock
// use this flag to control release all acquired locks
boolean lockConflict = false;
synchronized (bucketLockMap) {
                Long lockingTransactionId = bucketLockMap.get(pk);
                if (lockingTransactionId == null) {
                 //No existing lock
                 bucketLockMap.put(pk, transactionId);
                    Set<String> keysInHolder = bucketHolder.get(bucketLockMap);
                    if (keysInHolder == null) {
                        bucketHolder.putIfAbsent(bucketLockMap, new ConcurrentSet<String>());
                        keysInHolder = bucketHolder.get(bucketLockMap);
                    }
                    keysInHolder.add(pk);

                } else if (lockingTransactionId.longValue() == transactionId) {
                    // Locked by me
                    continue;
                } else {
                    lockConflict = true;
                    LOGGER.info("Global lock on [" + tableName + ":" + pk + "] is holding by " + lockingTransactionId);
                }
            }
            // Release all acquired locks without holding bucket monitor lock
            if (lockConflict) {
                try {
                    // Release all acquired locks.
                    branchSession.unlock();
                } catch (TransactionException e) {
                    throw new FrameworkException(e);
                }
                return false;
}
```

There is another solution to fix deadlock: sort PK list in alphabetical order before acquire these locks, this solution not only could resolve this problem, but also bring another advantage, i will talk about that later. Now go back to lock release process, i think it's necessary to take it out from bucket lock scope, because there isn't the place it should to be.It could reduce code risk of deadlock, and reduce bucket monitor lock's holding duration.

Now let's talk about advantage of sorting PK lock list. If two branch transaction concurrently execute with different PK list order, these two BTs will both failed, of course RM will retry to acquire PK locks, but may failure again, and in extreme cases, such a scenario will always be staged.Once you make these two branch transaction execute with same PK list order, always one BT could execute normally.

Acquire locks in same order:
```
2019-09-06 14:52:23.472 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:115 -Global lock on [t:1] is holding by 1001
2019-09-06 14:52:23.492 INFO [Thread-2]io.seata.common.loader.EnhancedServiceLoader.loadFile:237 -load Locker[file] extension by class[io.seata.server.lock.memory.MemoryLocker]
Result: first is true ,second is false
```
Acquire locks in different order:
```
2019-09-06 15:10:16.804 INFO [Thread-2]io.seata.core.lock.AbstractLocker.acquireLock:115 -Global lock on [t:3] is holding by 1001
2019-09-06 15:10:16.804 INFO [Thread-1]io.seata.core.lock.AbstractLocker.acquireLock:115 -Global lock on [t:4] is holding by 1002
2019-09-06 15:10:16.822 INFO [Thread-2]io.seata.common.loader.EnhancedServiceLoader.loadFile:237 -load Locker[file] extension by class[io.seata.server.lock.memory.MemoryLocker]
Result: first is false ,second is false
```
In summary, i think sort PK list before acquire locks is vary helpful. If you guys highly care about TC's performance, could do this work in RM and make sure PK list order could been kept until acquiring locks.
### Ⅵ. Environment:

- JDK version : 1.8
- OS : MacOS
- Others:

### PR DESCRIPTION
**Pull request by BeiKeJieDeLiuLangMao**
### Ⅰ. Describe what this PR did
Fix deadlock of MemoryLocker & sort locks by PK before acquire.

### Ⅱ. Does this pull request fix one issue?

Fixed  #1603.

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
No, i add one, it is `io.seata.server.lock.LockManagerTest#deadlockTest`.

### Ⅳ. Describe how to verify it
Run `io.seata.server.lock.LockManagerTest#deadlockTest`.

### Ⅴ. Special notes for reviews
All description is in #1603.

### CODE REVIEW

**Comment by Justice-love** [comment]
``` java
            Long lockingTransactionId = null;
            synchronized (bucketLockMap) {
                lockingTransactionId = bucketLockMap.get(pk);
                if (lockingTransactionId == null) {
                    //No existing lock
                    bucketLockMap.put(pk, transactionId);
                }
            }
```

**Comment by BeiKeJieDeLiuLangMao** [comment]
@Justice-love 
In fact, bucketLockMap is a ConcurrentHashMap too, i think this is enough:
```java
Long previousTransactionId = bucketLockMap.putIfAbsent(pk, transactionId);
if (previousTransactionId == null) {
    //No existing lock
    Set<String> keysInHolder = bucketHolder.get(bucketLockMap);
    if (keysInHolder == null) {
        bucketHolder.putIfAbsent(bucketLockMap, new ConcurrentSet<String>());
        keysInHolder = bucketHolder.get(bucketLockMap);
    }
    keysInHolder.add(pk);

} else if (previousTransactionId == transactionId) {
    // Locked by me
    continue;
} else {
    LOGGER.info("Global lock on [" + tableName + ":" + pk + "] is holding by " + previousTransactionId);
    try {
        // Release all acquired locks.
        branchSession.unlock();
    } catch (TransactionException e) {
        throw new FrameworkException(e);
    }
    return false;
}
```

**Comment by Justice-love** [comment]
> @Justice-love
> In fact, bucketLockMap is a ConcurrentHashMap too, i think this is enough:
> 
> ```java
> Long previousTransactionId = bucketLockMap.putIfAbsent(pk, transactionId);
> if (previousTransactionId == null) {
>     //No existing lock
>     Set<String> keysInHolder = bucketHolder.get(bucketLockMap);
>     if (keysInHolder == null) {
>         bucketHolder.putIfAbsent(bucketLockMap, new ConcurrentSet<String>());
>         keysInHolder = bucketHolder.get(bucketLockMap);
>     }
>     keysInHolder.add(pk);
> 
> } else if (previousTransactionId == transactionId) {
>     // Locked by me
>     continue;
> } else {
>     LOGGER.info("Global lock on [" + tableName + ":" + pk + "] is holding by " + previousTransactionId);
>     try {
>         // Release all acquired locks.
>         branchSession.unlock();
>     } catch (TransactionException e) {
>         throw new FrameworkException(e);
>     }
>     return false;
> }
> ```

i known, there is no problem code like this. but i think appropriate range of synchronized block is the basic rule.

**Comment by BeiKeJieDeLiuLangMao** [comment]
@Justice-love 
I understand your opinion, we do should be careful about range of synchronized block. What i wanted to express before is, instead of using synchronized block, we could better use ConcurrentHashMap's thread safe api. That is more powerful in performance than synchronized block.

**Comment by ggndnn** [comment]
@BeiKeJieDeLiuLangMao 
Based on the latest code, can we delete the `synchronized (bucket)` in `releaseLock`?

**Comment by ggndnn** [comment]
@BeiKeJieDeLiuLangMao If a branch session could unlock itself in parallel, there will be a problem without the synchronized in releaseLock. Do you think it's possible?

**Comment by BeiKeJieDeLiuLangMao** [comment]
@ggndnn 
I only delete `synchronized (bucket)` in `acquireLock` method, i think we could alse delete that in `releaseLock` method, after do that, the `releaseLock` method will like follow:
```java
@Override
public boolean releaseLock(List<RowLock> rowLock) {
    ConcurrentHashMap<ConcurrentHashMap<String, Long>, Set<String>> lockHolder = branchSession.getLockHolder();
    if (lockHolder == null || lockHolder.size() == 0) {
        return true;
    }
    Iterator<Map.Entry<ConcurrentHashMap<String, Long>, Set<String>>> it = lockHolder.entrySet().iterator();
    while (it.hasNext()) {
        Map.Entry<ConcurrentHashMap<String, Long>, Set<String>> entry = it.next();
        ConcurrentHashMap<String, Long> bucket = entry.getKey();
        Set<String> keys = entry.getValue();
        for (String key : keys) {
            bucket.remove(key, branchSession.getTransactionId());
        }
    }
    lockHolder.clear();
    return true;
}
```
And i am thinking about the problem what your talk about. If concurrently invoke `acquireLock` and `releaseLock`, and `releaseLock` finish first, `acquireLock` method maybe add new locks to `LOCK_MAP`. The problem is nobody will remove these new locks .

**Comment by ggndnn** [comment]
@BeiKeJieDeLiuLangMao 
Just for discussion, what about to use CAS instead of synchronized, a little complicated. Compare transactionId first, then remove, instead of removing directly. What's your opinion?

```
private static final long IMPOSSIBLE_TRANSACTION_ID = Long.MIN_VALUE;

private static final ConcurrentHashMap<String/* resourceId */,
    ConcurrentHashMap<String/* tableName */,
        ConcurrentHashMap<Integer/* bucketId */,
            Map<String/* pk */, AtomicLong/* transactionId */>>>>
    LOCK_MAP
    = new ConcurrentHashMap<>();


...

@Override
    public boolean acquireLock(List<RowLock> rowLocks) {
        for (RowLock lock : rowLocks) {
            ...
            AtomicLong lockingTransactionId = bucketLockMap.get(pk);
            if (lockingTransactionId == null) {
                lockingTransactionId = bucketLockMap.putIfAbsent(pk, new AtomicLong(transactionId));
            }
            while (lockingTransactionId != null && lockingTransactionId.get() == IMPOSSIBLE_TRANSACTION_ID) {
                lockingTransactionId = bucketLockMap.putIfAbsent(pk, new AtomicLong(transactionId));
            }
            if (lockingTransactionId == null) {
                //No existing lock
                Set<String> keysInHolder = bucketHolder.get(bucketLockMap);
                if (keysInHolder == null) {
                    bucketHolder.putIfAbsent(bucketLockMap, new ConcurrentSet<>());
                    keysInHolder = bucketHolder.get(bucketLockMap);
                }
                keysInHolder.add(pk);
            } else if (lockingTransactionId.longValue() != transactionId) {
                LOGGER.info("Global lock on [" + tableName + ":" + pk + "] is holding by " + lockingTransactionId);
                try {
                    // Release all acquired locks.
                    branchSession.unlock();
                } catch (TransactionException e) {
                    throw new FrameworkException(e);
                }
                return false;
            }
        }
        return true;
    }

    @Override
    public boolean releaseLock(List<RowLock> rowLock) {
        Iterator<Map.Entry<Map<String, AtomicLong>, Set<String>>> it = lockHolder.entrySet().iterator();
        while (it.hasNext()) {
            ...
            for (String key : keys) {
                AtomicLong v = bucket.get(key);
                if (v == null) {
                    continue;
                }
                if(v.compareAndSet(branchSession.getTransactionId(), IMPOSSIBLE_TRANSACTION_ID)) {
                    bucket.remove(key);
                }
            }
        }
        ...
    }
```

**Comment by BeiKeJieDeLiuLangMao** [comment]
@ggndnn 
In fact, ConcurrentHashMap's api provides CAS feature，you could take a look document of `java.util.Map#putIfAbsent` `java.util.Map#remove(java.lang.Object, java.lang.Object)`
> If the specified key is not already associated with a value (or is mapped
     * to {@code null}) associates it with the given value and returns
     * {@code null}, else returns the current value.

> Removes the entry for the specified key only if it is currently
     * mapped to the specified value.

So, use `java.util.Map#putIfAbsent` and `java.util.Map#remove(java.lang.Object, java.lang.Object)` is enough.

**Comment by ggndnn** [comment]
@BeiKeJieDeLiuLangMao 
Yes, same logic, but ConcurrentHashMap's implementation used `synchronized`... Never mind :), that's not the point here, I didn't notice your code above, it was more concise, my paste was just a logic presentation. Come back to this PR, I think it's enough, releaseLock success means key lock is released, acquireLock success means lock is acquired. What's your opinion?

**Comment by BeiKeJieDeLiuLangMao** [comment]
@ggndnn 
What i worry about is, is that possible branchSession's lock and unlock methods both invoked in same time.

I reviewed the code about lock and unlock.
There are two point, which will use `branchSession::lock`:
1. SessionHolder::reload: This process wil finish before open rpcServer server, we don't need to care about it because i think it's safe.
2. DefaultCore::branchRegister: In this method, `branchSession::lock` will been invoked with GlobalSession's lock, i think it's safe too.

Now let's pay attention to unlock process:
1. DefaultCore#branchRegister: if add branch failed, it will remove branchSession's lock, this invoked in globalSession's lock, so it's safe.
2. MemoryLocker#acquireLock: lock conflict, release locks just acqurired, because all branchSession's lock invoked in globalSession's lock, so it's safe.
3. DefaultCore#doGlobalCommit & doGlobalRollback: In invoke stack, only changing global session status process use GlobalSession's lock, but it could promise the whole globalSession safe.

Now let's consider follow situation:
1. TM register a globalSession in TC
2. TM invoke a RPC to RM1, but timeout, so TM wanna do global rollback.
3. But TM's RPC request received by RM1 actually, and RM1 try to register branch transaction in TC.
4. Unfortunately, RM1‘s register branch request and TM's global rollback request arrive TC at same time.
5. Branch register process begin firstly, in this time global session's status is `GlobalStatus.Begin`, but before add branchSession's locks, global rollback process begin to work.
6. Because global rollback process use global session's lock when change session status, if any branch register process not finish, it coun't get the global session's lock, after branch register process finish, it gets the lock and changes global session's status. After this moment, others branch register process could naver begin, because when hold the global session's lock to check session's status, it will find session is end, then it will fastfail.

Finally, i think the whole process is safe.

I will commit the code what i show you before. And as you said, ConcurrentHashMap's api uses synchronized block, but only happe when hash conflict, bucketMap's hash conflict, very low possibility i think.

**Comment by ggndnn** [comment]
@BeiKeJieDeLiuLangMao 
I understand your worries, maybe, it's not going to happen in my understanding of this project. Your analysis is good and detailed. It's very happy discussing here with you.

By the way. I said synchronized, i was just a joke, as I said, never mind. ConcurrentMap is good enough, though we used synchronized, jvm may use spinlock first. And hash conflict is not the condition whether synchronized block was used, I think your meaning was something like `Only when hash conflict there will be lock competition`.

Your code looks good to me now. Maybe someone else needs further review.

File: server/src/main/java/io/seata/server/lock/memory/MemoryLocker.java [hunk 1]
```diff
@@ -71,7 +71,7 @@ public boolean acquireLock(List<RowLock> rowLocks) {
         String resourceId = branchSession.getResourceId();
         long transactionId = branchSession.getTransactionId();
 
-        ConcurrentHashMap<Map<String, Long>, Set<String>> bucketHolder = branchSession.getLockHolder();
+        ConcurrentHashMap<ConcurrentHashMap<String, Long>, Set<String>> bucketHolder = branchSession.getLockHolder();
```
Comment (ggndnn) [inline server/src/main/java/io/seata/server/lock/memory/MemoryLocker.java]: Do we have to change the type declaration to `ConcurrentHashMap`?

Comment (BeiKeJieDeLiuLangMao) [reply server/src/main/java/io/seata/server/lock/memory/MemoryLocker.java]: I think it is appropriate to use ConcurrentHashMap to declare bucket map, it could help next guy understand why it's thread safe.

Comment (ggndnn) [reply server/src/main/java/io/seata/server/lock/memory/MemoryLocker.java]: Ok, it's helpful.

File: server/src/test/java/io/seata/server/lock/LockManagerTest.java [hunk 2]
```diff
@@ -123,12 +164,25 @@ public void isLockableTest(BranchSession branchSession) throws Exception {
...
-        branchSession2.setResourceId("tb_1");
-        branchSession2.setLockKey("t:1,2");
+        branchSession2.setResourceId(resource);
+        branchSession2.setLockKey(lockKey2);
         branchSession2.setBranchType(BranchType.AT);
         branchSession2.setApplicationData("{\"data\":\"test\"}");
         branchSession2.setBranchType(BranchType.AT);
         return Stream.of(
-                Arguments.of(branchSession1, branchSession2));
+            Arguments.of(branchSession1, branchSession2));
```
Comment (ggndnn) [inline server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Please keep the indentation same as other functions.

Comment (BeiKeJieDeLiuLangMao) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: OK

File: server/src/test/java/io/seata/server/lock/LockManagerTest.java [hunk 3]
```diff
@@ -62,6 +66,43 @@ public void acquireLock_failed(BranchSession branchSession1, BranchSession branc
...
+     * @param branchSession1 the branch session 1
+     * @param branchSession2 the branch session 2
+     * @throws Exception the exception
+     */
+    @ParameterizedTest
+    @MethodSource("deadlockBranchSessionsProvider")
+    public void deadlockTest(BranchSession branchSession1, BranchSession branchSession2) throws Exception {
+        LockManager lockManager = new MemoryLockManagerForTest();
+        final AtomicBoolean first = new AtomicBoolean();
+        final AtomicBoolean second = new AtomicBoolean();
```
Comment (ggndnn) [inline server/src/test/java/io/seata/server/lock/LockManagerTest.java]: What's the first and second variable used for?

Comment (BeiKeJieDeLiuLangMao) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Before find the deadlock bug, i use them to make sure two concurrent branchSession register process with different row key list, at least one process could success.
Now i split that test case to another method.

Comment (ggndnn) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Ok, you lost that test case, now add a new function `concurrentUseAbilityTest` to make use of these two variables.

File: server/src/test/java/io/seata/server/lock/LockManagerTest.java [hunk 4]
```diff
@@ -62,6 +66,84 @@ public void acquireLock_failed(BranchSession branchSession1, BranchSession branc
...
+                second.set(lockManager.acquireLock(branchSession2));
+            } catch (TransactionException e) {
+                e.printStackTrace();
+            } finally {
+                countDownLatch.countDown();
+            }
+        }).start();
+        // Assume execute more than 5 seconds means deadlock happened.
+        if (countDownLatch.await(5, TimeUnit.SECONDS)) {
+            Assertions.assertTrue(first.get() || second.get());
```
Comment (ggndnn) [inline server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Should the assertion be (first && !second) || (!first && second)?

File: server/src/test/java/io/seata/server/lock/LockManagerTest.java [hunk 5]
```diff
@@ -62,6 +66,84 @@ public void acquireLock_failed(BranchSession branchSession1, BranchSession branc
...
+        }
```
Comment (ggndnn) [inline server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Should the assertion be (first && !second) || (!first && second)?

Comment (BeiKeJieDeLiuLangMao) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Based on single responsibility principle, first || second is enough.
I think `LockManagerTest#acquireLock_failed` already do what you want to do.

Comment (ggndnn) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: If you said so, you lost some test cases, this test case concurrentUseAbilityTest only test `at least one process could success in concurrent case`, but `LockManagerTest#acquireLock_failed` is not responsible for concurrent use case. I think your assertion is not enough. What do you think?

Comment (ggndnn) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: I think no harm done to make this assertion completion, it has nothing to do with `responsibility principle`.

Comment (BeiKeJieDeLiuLangMao) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: OK, i understand.

Comment (ggndnn) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Based on the latest code, don't you think if first and second are both fail, this test case should be fail?

Comment (BeiKeJieDeLiuLangMao) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: This only happen on some guy acquires table locks（tb_2，t:1,2,3,4,5）and doesn't release them. 
At now, both methods which use these table locks will release them.

Comment (ggndnn) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: So, should we change the assertion `Assertions.assertTrue((first.get() && !second.get()) || (second.get() || !first.get()))` now?

Comment (BeiKeJieDeLiuLangMao) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Done a hour ago.

Comment (ggndnn) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: I think it should be `(first.get() && !second.get()) || (second.get() && !first.get())`. When second and first are both false, the test case should be fail.

Comment (BeiKeJieDeLiuLangMao) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: Sorry, i miswrite.

Comment (ggndnn) [reply server/src/test/java/io/seata/server/lock/LockManagerTest.java]: No problem. Thanks.

**Comment by xingfudeshi** [comment]
The Unit testing is passed.

**Comment by xingfudeshi** [comment]
@BeiKeJieDeLiuLangMao You need to associate your github account.
`git config --global user.email xxx@xxxx.com`
The email should be same as your github account.

**Comment by BeiKeJieDeLiuLangMao** [comment]
@xingfudeshi 
I finished, what should i do further?

**Comment by xingfudeshi** [comment]
> @xingfudeshi
> I finished, what should i do further?

Please re-push the commit.

**Comment by slievrly** [comment]
@BeiKeJieDeLiuLangMao https://github.com/seata/seata/issues/1603#issuecomment-531827136

File: server/src/main/java/io/seata/server/lock/DefaultLockManager.java [hunk 6]
```diff
@@ -61,6 +62,8 @@ public boolean acquireLock(BranchSession branchSession) throws TransactionExcept
             //no lock
             return true;
         }
+        //sort locks of branch by pk, if this influence performance, could move this work to RM
+        locks.sort(Comparator.comparing(RowLock::getPk));
```
Comment (slievrly) [inline server/src/main/java/io/seata/server/lock/DefaultLockManager.java]: Revoke the changes here. Because of the large-scale batch insertion scenario, this is a performance loss that does not actually lock conflicts.

Comment (BeiKeJieDeLiuLangMao) [reply server/src/main/java/io/seata/server/lock/DefaultLockManager.java]: OK
