### PR TITLE
fix #878 close the statement

### LINKED ISSUE #878: statement should close
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
statement should close

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
statement should close，when we use DruidPooledPreparedStatement we can use cache

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by github-ygy**
### Ⅰ. Describe what this PR did
when over，close the statement，if we use DruidPooledPreparedStatement，so wo can use cache

### Ⅱ. Does this pull request fix one issue?

fix #878

### CODE REVIEW

File: rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java [hunk 1]
```diff
@@ -239,24 +238,34 @@ public static void undo(DataSourceProxy dataSourceProxy, String xid, long branch
...
+            deletePST = conn.prepareStatement(batchDeleteSql);
+            int paramsIndex = 1;
+            for (Long branchId : branchIds) {
+                deletePST.setLong(paramsIndex++,branchId);
+            }
+            for (String xid: xids){
+                deletePST.setString(paramsIndex++, xid);
+            }
+            int deleteRows = deletePST.executeUpdate();
+            if (LOGGER.isInfoEnabled()) {
```
Comment (leizhiyuan) [inline rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java]: maybe this log level should be debug?

Comment (github-ygy) [reply rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java]: thanks，done
