### PR TITLE
Cache configuration instance.

### LINKED ISSUE #1077: ConfigurationFactory getInstance has no cache.
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

I found that this method `ConfigurationFactory.getInstance()` is used in many places, but I noticed that there is no cache. Is this really okay?

```
    public static Configuration getInstance() {
        ConfigType configType = null;
        String configTypeName = null;
        try {
            configTypeName = FILE_INSTANCE.getConfig(ConfigurationKeys.FILE_ROOT_CONFIG + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
                + ConfigurationKeys.FILE_ROOT_TYPE);
            configType = ConfigType.getType(configTypeName);
        } catch (Exception exx) {
            throw new NotSupportYetException("not support register type: " + configTypeName);
        }
        if (ConfigType.File == configType) {
            String pathDataId = ConfigurationKeys.FILE_ROOT_CONFIG + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
                + FILE_TYPE + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
                + NAME_KEY;
            String name = FILE_INSTANCE.getConfig(pathDataId);
            return new FileConfiguration(name);   <---- here
        } else {
            return EnhancedServiceLoader.load(ConfigurationProvider.class, Objects.requireNonNull(configType).name()).provide();
        }
    }
```

### PR DESCRIPTION
**Pull request by ujjboy**
### Ⅰ. Describe what this PR did

- Cache singleton configuration instance.

### Ⅱ. Does this pull request fix one issue?
Fix #1077

### CODE REVIEW

File: discovery/seata-discovery-core/src/test/java/io/seata/config/ConfigurationFactoryTest.java [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package io.seata.config;
```
Comment (xingfudeshi) [inline discovery/seata-discovery-core/src/test/java/io/seata/config/ConfigurationFactoryTest.java]: copyright

File: discovery/seata-discovery-core/src/test/java/io/seata/config/ConfigurationFactoryTest.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+/**
+ * @author <a href="mailto:zhanggeng.zg@antfin.com">GengZhang</a>
```
Comment (xingfudeshi) [inline discovery/seata-discovery-core/src/test/java/io/seata/config/ConfigurationFactoryTest.java]: remove a tag

**Comment by ujjboy** [comment]
@xingfudeshi done.
