### PR TITLE
optimize: optimize get config type from configuration

### LINKED ISSUE #2724: get configTypeName a little flaw
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
when building a configuration, there are insufficient prompts for configuration items that do not exist or are not supported
当配置不存在或者不支持时,无法从异常提示中捕捉到对应的问题

question 1: not support register type should change to not support config type
问题1:not support register type: 应该改为not support config type:

question 2: the prompt that the configuration type that cannot be read and the configuration type is empty should be separated
问题2:应该将不支持配置中心类型,跟读不到配置中心类型的异常提示区分开

有兴趣处理的同学,可以回复你要认领即可
if you are interested in dealing with this problem, you can reply, please assign it to me

image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by PeineLiang**
### Ⅰ. Describe what this PR did
fix: get configTypeName exception

### Ⅱ. Does this pull request fix one issue?
fixes #2724

### CODE REVIEW

File: config/seata-config-core/src/main/java/io/seata/config/ConfigType.java [hunk 1]
```diff
@@ -66,6 +66,6 @@ public static ConfigType getType(String name) {
                 return configType;
             }
         }
-        throw new IllegalArgumentException("illegal type:" + name);
+        throw new IllegalArgumentException("not support config type: " + name);
```
Comment (l81893521) [inline config/seata-config-core/src/main/java/io/seata/config/ConfigType.java:69]: How about do not change here?

File: config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java [hunk 2]
```diff
@@ -101,9 +102,14 @@ private static Configuration buildConfiguration() {
             configTypeName = CURRENT_FILE_INSTANCE.getConfig(
                 ConfigurationKeys.FILE_ROOT_CONFIG + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
                     + ConfigurationKeys.FILE_ROOT_TYPE);
+
+            if (StringUtils.isEmpty(configTypeName)) {
```
Comment (l81893521) [inline config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java:106]:
```
if (configTypeName == null)
```
That s enough.

Comment (l81893521) [reply config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java:106]: Because if
```
configTypeName.equals("")
```
ConfigType.getType would throw exception.

File: config/seata-config-core/src/main/java/io/seata/config/ConfigType.java (hunk 1 above)
Comment (PeineLiang) [reply config/seata-config-core/src/main/java/io/seata/config/ConfigType.java:69]: Because this is the getType method of the Enum class, the reason for the exception here is that the input parameter is illegal.

File: config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java [hunk 3]
```diff
@@ -101,9 +102,14 @@ private static Configuration buildConfiguration() {
...
                     + ConfigurationKeys.FILE_ROOT_TYPE);
+
+            if (StringUtils.isBlank(configTypeName)) {
+                throw new NotSupportYetException("can not get config type: " + configTypeName);
+            }
+
             configType = ConfigType.getType(configTypeName);
         } catch (Exception e) {
-            throw new NotSupportYetException("not support register type: " + configTypeName, e);
+            throw e;
```
Comment (l81893521) [inline config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java:112]: If throw it directly, is it would throw other exception?

File: config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java [hunk 4]
```diff
@@ -101,9 +102,14 @@ private static Configuration buildConfiguration() {
             configTypeName = CURRENT_FILE_INSTANCE.getConfig(
                 ConfigurationKeys.FILE_ROOT_CONFIG + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
                     + ConfigurationKeys.FILE_ROOT_TYPE);
+
+            if (StringUtils.isBlank(configTypeName)) {
+                throw new NotSupportYetException("can not get config type: " + configTypeName);
```
Comment (slievrly) [inline config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java:107]: configTypeName is blank，why not print it out explicitly？

Comment (PeineLiang) [reply config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java]: you are right ,i change the message to "config type can not be null"
