### PR TITLE
bugfix:fix the value of disableGlobalTransaction not being read correctly

### LINKED ISSUE #2114: 将配置参数改为application.yml后的问题
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
尝试将registry.conf和file.conf配置到application.yml中，目前发现一下两个问题，
1. undo相关配置不生效（估计seata.client.rm.lock相关属性也有类似问题）
2. service.disable-global-transaction不生效

### Ⅱ. Describe what happened
application.yml的配置
```
seata:
  enabled: true
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm-report-success-enable: true
    rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
    rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
    rm-async-commit-buffer-limit: 1000 # 异步提交缓存队列长度（默认10000）
    rm:
      lock:
        lock-retry-internal: 10 # 校验或占用全局锁重试间隔（默认10ms）
        lock-retry-times:    30 # 校验或占用全局锁重试次数（默认30）
        lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm-commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
      undo-log-serialization: jackson # undo序列化方式（默认jackson）
      undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
    support:
      spring-datasource-autoproxy: true # 数据源自动代理开关（默认false关闭）
  service:
    vgroup-mapping: default # TC 集群（必须与seata-server保持一致）
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
  transport:
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  registry:
    type: eureka
    eureka:
      serviceUrl: ${eureka.host}
```
#### 问题1分析：undo相关配置不生效
`UndoProperties`中的属性有undo前缀
```
@ConfigurationProperties(prefix = UNDO_PREFIX)
public class UndoProperties {
    private boolean undoDataValidation = true;
    private String undoLogSerialization = "jackson";
    private String undoLogTable = TRANSACTION_UNDO_LOG_DEFAULT_TABLE;
    ...
}
```
而跟踪到`SpringBootConfigurationProvider`的103行时，却获取的是`seata.client.undo.logTable`
```
    private Object get(String dataId) throws IllegalAccessException {
// 此时拿到的dataId = seata.client.undo.logTable
        String propertySuffix = getPropertySuffix(dataId);
        Class propertyClass = getPropertyClass(getPropertyPrefix(dataId));
        if (null != propertyClass) {
            Object propertyObject = SpringUtils.getBean(propertyClass);
            Optional<Field> fieldOptional = Stream.of(propertyObject.getClass().getDeclaredFields()).filter(
                f -> f.getName().equalsIgnoreCase(propertySuffix)).findAny();
// 因为属性中只有undoLogTable，没有logTable，因此此时读取不到yml中的配置，返回null，采用系统默认
            if (fieldOptional.isPresent()) {
                Field field = fieldOptional.get();
                field.setAccessible(true);
                return field.get(propertyObject);
            }
        }
        return null;
    }
```
#### 问题2分析： service.disable-global-transaction不生效
跟踪代码，确实取到yml中的配置了，但是后面还是输出错误
```
[2019-12-31 10:55:43.746] [configOperate_2_2] [WARN ] io.seata.config.FileConfiguration [266] - Could not found property service.disableGlobalTransaction, try to use default value instead.
```
然后增加一个`file.conf`，添加以下内容，在启动时则没有该错误
```
service {
  disableGlobalTransaction = false
}
```

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win10、centos7
- seata: 1.0.0
- seata-spring-boot-starter : 1.0.0

### PR DESCRIPTION
**Pull request by xingfudeshi**
### Ⅰ. Describe what this PR did
fix the value of disableGlobalTransaction not being read correctly.

### Ⅱ. Does this pull request fix one issue?

fixes #2114 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
I've done integration testing.

### CODE REVIEW

File: seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java [hunk 1]
```diff
@@ -67,9 +67,12 @@ public Object intercept(Object proxy, Method method, Object[] args, MethodProxy
                         result = get(convertDataId(rawDataId), args[1], (Long) args[2]);
                     }
                     if (null != result) {
+                        //If the return type is String,need to convert the object to string
+                        if (method.getReturnType().equals(String.class)) {
```
Comment (slievrly) [inline seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java]: What about the rest? Such as getBoolean 、 getShort、getInt、getLong？

Comment (xingfudeshi) [reply seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java]: GetConfig converts the values of all configuration items to strings and returns them. Other methods, such as getShort, do not require such a transformation. And Boolean cannot be cast to String.
