### PR TITLE
bugfix: fix register branch and flush undolog when affect row was zero

### LINKED ISSUE #3521: seata1.3 at模式下 偶发出现 locktable写入时主键重复
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
TC端偶发的报错 看异常信息应该是写入locktable时主键重复

### Ⅱ. Describe what happened
偶发
TC端日志 
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'jdbc:mysql://10.5.9.42:3306/interfacecenter^^^t_dmsif_jk003_01' for
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.doAcquireLock(LockStoreDataBaseDAO.java:313)
        ... 24 common frames omitted

客户端日志
PreparedStatementCallback; uncategorized SQLException for SQL [DELETE FROM T_DMSIF_JK513_01 WHERE IIDMS_ID =? ]; SQL state [null]; error code [0]; io.seata.core.exception.RmTransactionException: Response[ TransactionException[branch register request failed. xid=10.128.45.55:8091:105037255928934400, msg=Duplicate entry 'jdbc:mysql:/ ]; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[branch register request failed. xid=10.128.45.55:8091:105037255928934400, msg=Duplicate entry 'jdbc:mysql:/ ]

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : openshift 
- Others: springboot 2.1.9

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

bugfix: fix register branch and flush undolog when affect row was zero

### Ⅱ. Does this pull request fix one issue?
fix #3521

### CODE REVIEW

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 1]
```diff
@@ -279,10 +278,12 @@ protected void prepareUndoLog(TableRecords beforeImage, TableRecords afterImage)
 
         TableRecords lockKeyRecords = sqlRecognizer.getSQLType() == SQLType.DELETE ? beforeImage : afterImage;
         String lockKeys = buildLockKey(lockKeyRecords);
-        connectionProxy.appendLockKey(lockKeys);
+        if (null != lockKeys) {
```
Comment (a364176773) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:281]: maybe you can put it in the connectionProxy# appendLockKey function

**Comment by a364176773** [comment]
please add test case

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 1 above)
Comment (lightClouds917) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:281]: the method return value ,  is from :  
`StringBuilder sb = new StringBuilder();
xxx
return sb.toString();`
It can not use null != lockkeys, should use if(StringUtils.isBlank(lockKeys))

**Review by lightClouds917 — CHANGES_REQUESTED** [review]

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 1 above)
Comment (a364176773) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:281]: +1

Comment (slievrly) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:281]: If you put code in `connectionProxy# appendLockKey`, it will still execute L284~L285.

Comment (slievrly) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:281]:
```
if (rowsIncludingPK.size() == 0) {
            return null;
        }
```

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by l81893521 — APPROVED** [review]
LGTM
