### PR TITLE
bugfix: server restart not recover max sessionId on db mode

### LINKED ISSUE #1851: server restart not recover max sessionId on db mode
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
when startup on db mode, if server restart and there are some globalSession or branchSession left in global_table or branch_table, it may cause duplicates of transId or branchId to result in data that cannot be written to db.

so, where startup recover the max transId or branchId.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

bugfix: server restart not recover max sessionId on db mode

### Ⅱ. Does this pull request fix one issue?
fix #1851 

### Ⅳ. Describe how to verify it
image

### CODE REVIEW

File: core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java [hunk 1]
```diff
@@ -486,6 +486,49 @@ public boolean deleteBranchTransactionDO(BranchTransactionDO branchTransactionDO
...
+        Connection conn = null;
+        PreparedStatement ps = null;
+        try {
+            conn = logStoreDataSource.getConnection();
+            conn.setAutoCommit(true);
+            ps = conn.prepareStatement(sql);
+            ps.setLong(1, high);
+            ps.setLong(2, low);
+
+            ResultSet rs = ps.executeQuery();
```
Comment (zjinlei) [inline core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java]: recommended to close rs

File: core/src/main/java/io/seata/core/store/db/LogStoreSqls.java [hunk 2]
```diff
@@ -184,6 +184,20 @@
...
+    public static final String QUERY_MAX_TRANS_ID = "select max(" + ServerTableColumnsName.GLOBAL_TABLE_TRANSACTION_ID
+        + ") from " + GLOBAL_TABLE_PLACEHOLD + " where " + ServerTableColumnsName.GLOBAL_TABLE_TRANSACTION_ID
+        + " < ? and " + ServerTableColumnsName.GLOBAL_TABLE_TRANSACTION_ID + " > ?";
+
+    /**
+     * The constant CHECK_MAX_BTANCH_ID.
+     */
+    public static final String QUERY_MAX_BTANCH_ID = "select max(" + ServerTableColumnsName.BRANCH_TABLE_BRANCH_XID
+        + ") from " + BRANCH_TABLE_PLACEHOLD + " where " + ServerTableColumnsName.BRANCH_TABLE_BRANCH_XID + " < ? and "
+        + ServerTableColumnsName.BRANCH_TABLE_BRANCH_XID + " > ?";
```
[the remark this answers is not in the document]
Comment (slievrly) [reply core/src/main/java/io/seata/core/store/db/LogStoreSqls.java]: fixed.

File: core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java (hunk 1 above)
Comment (slievrly) [reply core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java]: fixed.

File: server/src/main/java/io/seata/server/session/db/DataBaseSessionManager.java [hunk 3]
```diff
@@ -183,4 +185,11 @@ public GlobalSession findGlobalSession(String xid) {
         return transactionStoreManager.readSession(condition);
     }
 
+    @Override
+    public void reload() {
+        long maxSessionId = transactionStoreManager.getCurrentMaxSessionId();
+        if (maxSessionId > UUIDGenerator.getCurrentUUID()) {
+            UUIDGenerator.setUUID(UUIDGenerator.getCurrentUUID(), maxSessionId + 1);
```
Comment (zjinlei) [inline server/src/main/java/io/seata/server/session/db/DataBaseSessionManager.java]: no need to add 1

File: server/src/main/java/io/seata/server/session/DefaultSessionManager.java [hunk 4]
```diff
@@ -51,6 +51,22 @@ public DefaultSessionManager(String name) {
...
                 return true;
             }
+
+            @Override
+            public long getCurrentMaxSessionId() {
+                long maxSessionId = 0L;
+                for (Map.Entry<String, GlobalSession> entry : sessionMap.entrySet()) {
+                    GlobalSession globalSession = entry.getValue();
+                    if (globalSession.hasBranch()) {
+                        long maxBranchId = globalSession.getSortedBranches().get(globalSession.getSortedBranches().size() - 1)
```
Comment (zjinlei) [inline server/src/main/java/io/seata/server/session/DefaultSessionManager.java]: getSortedBranches seems not implement?

File: server/src/main/java/io/seata/server/session/db/DataBaseSessionManager.java (hunk 3 above)
Comment (slievrly) [reply server/src/main/java/io/seata/server/session/db/DataBaseSessionManager.java]: fixed

File: server/src/main/java/io/seata/server/session/DefaultSessionManager.java (hunk 4 above)
Comment (slievrly) [reply server/src/main/java/io/seata/server/session/DefaultSessionManager.java]: Because the order is self-increasing the branchId, the added branchId is incremented.
