### PR TITLE
optimize: Modify  workerid generation method

### LINKED ISSUE #2785: need to optimize the current workerId generation rule of snowflake id
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
at present, the workerId is randomly generated from 0-1023, which is not elegant.I hope someone can solve this problem.

目前workerId 采用随机从0-1023中生成,并不优雅,希望有同学能解决这个问题.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by lj2018110133**
### Ⅰ. Describe what this PR did

Modify workerid generation method

### Ⅱ. Does this pull request fix one issue?

fix #2785

### CODE REVIEW

**Comment by a364176773** [comment]
the title prefix optimize:

File: common/src/main/java/io/seata/common/util/IdWorker.java [hunk 1]
```diff
@@ -144,12 +147,24 @@ public static IdWorker getInstance() {
...
+    public static long initWorkerId(){
+        InetAddress address;
+        try {
+            address = InetAddress.getLocalHost();
+        } catch (final UnknownHostException e) {
+            throw new IllegalStateException("Cannot get LocalHost InetAddress, please check your network!");
+        }
+        byte[] ipAddressByteArray = address.getAddress();
+        long workerId = (((ipAddressByteArray[ipAddressByteArray.length - 2] & 0B11) << Byte.SIZE) + (ipAddressByteArray[ipAddressByteArray.length - 1] & 0xFF));
+        Preconditions.checkArgument(workerId >= 0L && workerId < 1024L);
```
Comment (a364176773) [inline common/src/main/java/io/seata/common/util/IdWorker.java:165]: if according to the current practice, will the id be greater than 1023? if yes, it is not advisable to simply throw an exception

File: server/src/main/java/io/seata/server/ParameterParser.java [hunk 2]
```diff
@@ -49,7 +50,7 @@
 
     private static final int SERVER_DEFAULT_PORT = 8091;
     private static final String SERVER_DEFAULT_STORE_MODE = "file";
-    private static final Long SERVER_DEFAULT_NODE = ThreadLocalRandom.current().nextLong(1024);
+    private static final Long SERVER_DEFAULT_NODE = IdWorker.initWorkerId();
```
Comment (a364176773) [inline server/src/main/java/io/seata/server/ParameterParser.java:53]: whether the serverNode is null or out of range,do this again

File: common/src/main/java/io/seata/common/util/IdWorker.java (hunk 1 above)
Comment (lj2018110133) [reply common/src/main/java/io/seata/common/util/IdWorker.java]: No more than 1023, because according to the algorithm, the maximum 1111111111 is 1023

File: server/src/main/java/io/seata/server/ParameterParser.java (hunk 2 above)
Comment (lj2018110133) [reply server/src/main/java/io/seata/server/ParameterParser.java]: Already processed

File: integration/http/src/test/java/io/seata/integration/http/HttpTest.java [hunk 3]
```diff
@@ -40,7 +40,7 @@
  */
 class HttpTest {
 
-    private static final String host = "http://127.0.0.1:8081";
+    private static final String host = "http://127.0.0.1:8080";
```
Comment (a364176773) [inline integration/http/src/test/java/io/seata/integration/http/HttpTest.java:43]: ????why modify the port

File: common/src/main/java/io/seata/common/util/NumberUtils.java [hunk 4]
```diff
@@ -53,4 +53,11 @@ public static Long toLong(String str, final Long defaultValue) {
             return defaultValue;
         }
     }
+
+    public static Long toLong(String str) {
+        if (str != null) {
```
[the remark this answers is not in the document]
Comment (lj2018110133) [reply common/src/main/java/io/seata/common/util/NumberUtils.java:58]: Ok！ i will optimize it

File: common/src/main/java/io/seata/common/util/IdWorker.java [hunk 5]
```diff
@@ -144,13 +144,24 @@ public static IdWorker getInstance() {
...
 
+    public static long initWorkerId() {
+        InetAddress address;
+        try {
+            address = InetAddress.getLocalHost();
+        } catch (final UnknownHostException e) {
+            throw new IllegalStateException("Cannot get LocalHost InetAddress, please check your network!");
+        }
+        byte[] ipAddressByteArray = address.getAddress();
+        return ((ipAddressByteArray[ipAddressByteArray.length - 2] & 0B11) << Byte.SIZE) + (ipAddressByteArray[ipAddressByteArray.length - 1] & 0xFF);
```
Comment (slievrly) [inline common/src/main/java/io/seata/common/util/IdWorker.java:162]: Need to verify ipv6, why is it `&0B11` instead of some other number here?

Comment (slievrly) [inline common/src/main/java/io/seata/common/util/IdWorker.java:162]: need to verify ipv6 address.

File: common/src/main/java/io/seata/common/util/IdWorker.java [hunk 6]
```diff
@@ -144,13 +144,24 @@ public static IdWorker getInstance() {
...
         }
         return idWorker;
     }
 
+    public static long initWorkerId() {
+        InetAddress address;
+        try {
+            address = InetAddress.getLocalHost();
+        } catch (final UnknownHostException e) {
+            throw new IllegalStateException("Cannot get LocalHost InetAddress, please check your network!");
```
Comment (slievrly) [inline common/src/main/java/io/seata/common/util/IdWorker.java:159]: the exception information should contain e.

File: common/src/main/java/io/seata/common/util/IdWorker.java (hunk 5 above)
Comment (lj2018110133) [reply common/src/main/java/io/seata/common/util/IdWorker.java:162]: Ok i will handle it

File: common/src/main/java/io/seata/common/util/IdWorker.java [hunk 7]
```diff
@@ -144,13 +144,24 @@ public static IdWorker getInstance() {
...
                 if (idWorker == null) {
-                    init(ThreadLocalRandom.current().nextLong(1024));
+                    init(initWorkerId());
                 }
             }
         }
         return idWorker;
     }
 
+    public static long initWorkerId() {
```
Comment (l81893521) [inline common/src/main/java/io/seata/common/util/IdWorker.java:154]: I think it will always return int.

**Comment by jsbxyyx** [comment]
The same machine, multiple servers, how to solve?

File: common/src/main/java/io/seata/common/util/IdWorker.java (hunk 7 above)
Comment (lj2018110133) [reply common/src/main/java/io/seata/common/util/IdWorker.java:154]: Indeed, it will be dealt with next time
