### PR TITLE
bugfix: Lock is not acquired when multiple branches have cross locks#1247

### LINKED ISSUE #1247: RM failed to acquire lock
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

RM fails to acquire global lock for it's operated record.

### Ⅱ. Describe what happened

There are two RM in a global transaction. The first RM inserts a record, the second RM updated this record and another reocord **in a local transaction**.
When I pause global transaction after phase1 completed and before start phase2 where global lock isnot released. I find there is only one global lock record in TC's lock_table for the inserted record.

I check the code for acquiring Lock in DB mode, class `LockStoreDataBaseDAO.class`, method `public boolean acquireLock(List<LockDO> lockDOs)`, line 113 to line 135:

```
            //query
            String checkLockSQL = LockStoreSqls.getCheckLockableSql(lockTable, sb.toString(), dbType);
            ps = conn.prepareStatement(checkLockSQL);
            for (int i = 0; i < lockDOs.size(); i++) {
                ps.setString(i + 1, lockDOs.get(i).getRowKey());
            }
            rs = ps.executeQuery();
            while (rs.next()) {
                if (StringUtils.equals(rs.getString("xid"), lockDOs.get(0).getXid())) {
                    isReLock = true;
                } else {
                    canLock &= false;
                }
            }

            if (!canLock) {
                conn.rollback();
                return false;
            }

            if (isReLock) {
                conn.rollback();
                return true;
            }

```
There is a logic problem when RM try to acquire lock including the ones are acquired and the other are not acquired at the same time. TC find there exist relock so it jump out without acquring the other lock.

### III. Environment:

- JDK version : jdk1.8
- OS : linux
- Others: Seata 0.6.1

### PR DESCRIPTION
**Pull request by zjinlei**
### Ⅰ. Describe what this PR did
bugfix #1247 

### Ⅱ. Does this pull request fix one issue?

fixes #1247

### CODE REVIEW

File: core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java [hunk 1]
```diff
@@ -114,25 +120,29 @@ public boolean acquireLock(List<LockDO> lockDOs) {
             }
             rs = ps.executeQuery();
             while (rs.next()) {
-                if (StringUtils.equals(rs.getString("xid"), lockDOs.get(0).getXid())) {
-                    isReLock = true;
-                } else {
+                if (!StringUtils.equals(rs.getString("xid"), lockDOs.get(0).getXid())) {
                     canLock &= false;
+                    break;
```
Comment (slievrly) [inline core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java]: why break?
db: lock1:xid1   lock2:xid2  lock3:xid1
request: lock1:xid1  lock2:xid1  lock3:xid1

lock3 can add in dbExistedRowKeys?

Comment (zjinlei) [reply core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java]: db: lock2:xid2
request:  lock2:xid1
These two global transactions are different. You cannot get the lock this time.
add break is a quick failure

Comment (slievrly) [reply core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java]: agree
