### PR TITLE
bugfix:SPI load DataSourceManager, test module not function

### LINKED ISSUE #745: SPI load DataSourceManager, test module not function
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

SPI load DataSourceManager, test module not function

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by slievrly**
### Ⅰ. Describe what this PR did

bugfix:SPI load DataSourceManager, test module not function

### Ⅱ. Does this pull request fix one issue?
fix #745

### CODE REVIEW

File: common/src/main/java/com/alibaba/fescar/common/loader/EnhancedServiceLoader.java [hunk 1]
```diff
@@ -165,8 +166,6 @@
                     }
                 }
             }
-
-            // 为避免被覆盖，每个activateName的查找，允许再加一层子目录
```
Comment (xingfudeshi) [inline common/src/main/java/com/alibaba/fescar/common/loader/EnhancedServiceLoader.java]: please replace Chinese comments with English comments.

File: test/src/main/java/com/alibaba/fescar/test/LocalTransactionWithGlobalLockDataSourceBasicTest.java [hunk 2]
```diff
@@ -245,23 +241,37 @@ public BranchStatus branchRollback(BranchType branchType, String xid, long branc
...
-        directJdbcTemplate.execute("delete from user0");
-        directJdbcTemplate.execute("delete from user1");
+                boolean exceptionOccour = false;
+                try {
+                    doExecute();
+                } catch (UncategorizedSQLException e) {
+                    exceptionOccour = true;
+                    Assert.assertTrue("not lock Conflict exception", e.getMessage().contains("LockConflict"));
+                } finally {
+                    DataSourceManager.set(new MockDataSourceManager());
```
Comment (github-ygy) [inline test/src/main/java/com/alibaba/fescar/test/LocalTransactionWithGlobalLockDataSourceBasicTest.java]: do not use DataSourceManager
