### PR TITLE
bugfix: when run server Module ServerTest failed, it occur "hostname can't be null" errors. see issue #743

### LINKED ISSUE #743: The server Module ServerTest failed, it occur "hostname can't be null" errors
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I downloads the newest source code, get the dependencies, open the server module run the ServerTest.java , it has errors. After traceing the errors, I found the code execute on this line 
" RegistryFactory.getInstance().register(new InetSocketAddress(XID.getIpAddress(), XID.getPort()));" in AbstractRpcRemotingServer.java file, the error just happend.  It seem that XID have no values, so the XID.getIpAddress()'s call return null, then **CHECKHOST** method catch that and throw the exception.  SO I want to know  is there something wrong or I have some mistakes.
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
2019-04-08 14:53:21.436 INFO [main]c.a.fescar.core.rpc.netty.AbstractRpcRemotingServer.start:153 -Server started ... 
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: hostname can't be null
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:158)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:131)
	at ServerTest.main(ServerTest.java:46)
Caused by: java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:154)
	... 2 more
2019-04-08 14:53:21.452 INFO [ShutdownHook]com.alibaba.fescar.core.rpc.netty.RpcServer.destroy:177 -destroyed rpcServer

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. just downloads the newest source code 
2. get the dependencies ready
3. open the server module, run the ServerTest.java in test directory , then you will see the exception

### Ⅵ. Environment:

- JDK version :jdk1.8.0_172
- OS : windows 10
- Others:

### PR DESCRIPTION
**Pull request by codewaltz1994**
### Ⅰ. Describe what this PR did
FixBug #743 
When run server Module ServerTest failed, it occur "hostname can't be null" errors. see issue seata#743. According to logics in server.class just add XID set* ops into ServerTest class, then bug is free.

### Ⅱ. Does this pull request fix one issue?

fixes #743 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Because this bug occur in a test class

### Ⅳ. Describe how to verify it
just run ServerTest before and after this bugfix.

### CODE REVIEW

File: server/src/test/java/ServerTest.java [hunk 1]
```diff
@@ -42,8 +43,9 @@ public static void main(String[] args) {
         RpcServer rpcServer = new RpcServer(workingThreads);
         rpcServer.setHandler(new DefaultCoordinator(rpcServer));
```
Comment (leizhiyuan) [inline server/src/test/java/ServerTest.java]: please change this class to a test case, not main method.

Comment (codewaltz1994) [reply server/src/test/java/ServerTest.java]: Hi, according your advice, I have done with it.  but in server module , the original authors's tests used the Main method, you can view the original code for this , so I want to know that we need to be consistent with him, or should just fix the bug. THX.

Comment (xingfudeshi) [reply server/src/test/java/ServerTest.java]: > please change this class to a test case, not main method.

for this situation,i thinks it's not necessary to use @Test.otherwise,the server will never be closed.

Comment (leizhiyuan) [reply server/src/test/java/ServerTest.java]: you can use @ after to shutdown the test server

Comment (xingfudeshi) [reply server/src/test/java/ServerTest.java]: after the server started,the main thread will be block, the @after will not get a chance to execute.

Comment (codewaltz1994) [reply server/src/test/java/ServerTest.java]: @xingfudeshi Then should  I change the @Test method back to Main method which the original author does, and we just focus on the bugfix?

Comment (xingfudeshi) [reply server/src/test/java/ServerTest.java]: yes.

Comment (codewaltz1994) [reply server/src/test/java/ServerTest.java]: @xingfudeshi It had already done.

Comment (codewaltz1994) [reply server/src/test/java/ServerTest.java]: @leizhiyuan Hi, Add @Test and @After method seem not suitable for this case, No as good as we focus on bugfix. So I change back into Main mothod as the original author does.

**Comment by leizhiyuan** [comment]
LGTM

File: server/src/test/java/ServerTest.java (hunk 1 above)
Comment (codewaltz1994) [reply server/src/test/java/ServerTest.java]: @leizhiyuan Hi, since we have common in changes after we discussed before, please approve these changes, not request changes. after this, changes can be merge into develop branch, I think. Thanks all

**Comment by codewaltz1994** [comment]
Thanks all of you. It's my pleasure.
