### PR TITLE
bugfix: fix xidInterceptorType is null

### LINKED ISSUE #1908: AT模式下Dubbo集成报xidInterceptorType空指针异常
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
RootContext.java 第92行
当xidType==null时  会报空指针异常

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
java.lang.NullPointerException: null
	at io.seata.core.context.RootContext.bindInterceptorType(RootContext.java:92) ~[seata-all-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.seata.integration.dubbo.TransactionPropagationFilter.invoke(TransactionPropagationFilter.java:57) ~[seata-all-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:55) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:48) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:105) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:149) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:152) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) [dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) [dubbo-2.7.4.1.jar:2.7.4.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

### Ⅵ. Environment:

- Dubbo : 2.7.4.1 Apache包下的注解
- Seata Server: 0.9.0
- Seata Client: 1.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by cmonkey**
### Ⅱ. Does this pull request fix one issue?

fixes #1908

### CODE REVIEW

File: core/src/main/java/io/seata/core/context/RootContext.java [hunk 1]
```diff
@@ -89,6 +89,10 @@ public static void bind(String xid) {
      * @param xidType
      */
     public static void bindInterceptorType(String xidType) {
```
Comment (jsbxyyx) [inline core/src/main/java/io/seata/core/context/RootContext.java]:
```
public static void bindInterceptorType(String xidType) {
    if(StringUtils.isNotBlank(xidType)){
        String[] xidTypes = xidType.split("_");
        if(xidTypes.length == 2){
            bindInterceptorType(xidTypes[0], BranchType.valueOf(xidTypes[1]));
        }
    }
}
```

Comment (cmonkey) [reply core/src/main/java/io/seata/core/context/RootContext.java]: Has been modified
