### PR TITLE
bugfix: binding public network address listen failed

### LINKED ISSUE #1504: Binding public network listen failed
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

bugfix:binding public network address listen failed.

sh seata-server.sh -h $PUBLIC_ADDRESS_IP  -p 8091 -m file

### Ⅱ. Does this pull request fix one issue?
fix #1504

### CODE REVIEW

**Comment by xingfudeshi** [comment]
Considering the actual business scenario, Seata no longer supports specific IP for binding.

File: core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingServer.java [hunk 1]
```diff
@@ -175,7 +175,7 @@ public void initChannel(SocketChannel ch) {
         }
 
         try {
-            ChannelFuture future = this.serverBootstrap.bind(host, listenPort).sync();
+            ChannelFuture future = this.serverBootstrap.bind(listenPort).sync();
```
[the remark this answers is not in the document]
Comment (slievrly) [reply core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingServer.java]: -h is used for registration center registration ip, here to achieve the listen ip and registration ip separation, listen ip we can use localhost directly

**Comment by slievrly** [comment]
> Considering the actual business scenario, Seata no longer supports specific IP for binding.

In the business scenario, a VIP external service is required.

**Comment by zjinlei** [comment]
please remove ParameterParser SERVER_DEFAULT_BIND_IP

**Comment by xingfudeshi** [comment]
> please remove ParameterParser SERVER_DEFAULT_BIND_IP

It can't be removed as this parameter is actually use to specific IP that register to registry center.

**Comment by xingfudeshi** [comment]
Here 
image
the description need to be updated,"The IP to register to registry."

**Comment by slievrly** [comment]
> Here
> image
> the description need to be updated,"The IP to register to registry."

fixed

File: server/src/main/java/io/seata/server/ParameterParser.java [hunk 2]
```diff
@@ -34,11 +34,14 @@
     private static final String SERVER_DEFAULT_BIND_IP = "0.0.0.0";
```
Comment (xingfudeshi) [inline server/src/main/java/io/seata/server/ParameterParser.java]: this constan is no more required.Because 0.0.0.0 is a valid IP for registering to register center.

Comment (slievrly) [reply server/src/main/java/io/seata/server/ParameterParser.java]: fixed

File: server/src/main/java/io/seata/server/ParameterParser.java [hunk 3]
```diff
@@ -31,22 +31,29 @@
...
     private int port = SERVER_DEFAULT_PORT;
     @Parameter(names = {"--storeMode", "-m"}, description = "log store mode : file、db", order = 3)
     private String storeMode = CONFIG.getConfig(ConfigurationKeys.STORE_MODE, SERVER_DEFAULT_STORE_MODE);
     @Parameter(names = {"--serverNode", "-n"}, description = "server node id, such as 1, 2, 3. default is 1", order = 4)
     private int serverNode = SERVER_DEFAULT_NODE;
 
+    /**
+     * Instantiates a new Parameter parser.
+     *
+     * @param args the args
```
Comment (zjinlei) [inline server/src/main/java/io/seata/server/ParameterParser.java]: Abnormal description

File: server/src/main/java/io/seata/server/ParameterParser.java [hunk 4]
```diff
@@ -86,7 +93,7 @@ private void printError(ParameterException e) {
     /**
      * Gets host
      *
-     * @return host
+     * @return host host
```
Comment (zjinlei) [inline server/src/main/java/io/seata/server/ParameterParser.java]: Abnormal description

File: server/src/main/java/io/seata/server/ParameterParser.java [hunk 5]
```diff
@@ -95,7 +102,7 @@ public String getHost() {
     /**
      * Gets port
      *
-     * @return port
+     * @return port port
```
Comment (zjinlei) [inline server/src/main/java/io/seata/server/ParameterParser.java]: Abnormal description

File: server/src/main/java/io/seata/server/ParameterParser.java [hunk 6]
```diff
@@ -104,7 +111,7 @@ public int getPort() {
     /**
      * Gets store mode
      *
-     * @return storeMode
+     * @return storeMode store mode
```
Comment (zjinlei) [inline server/src/main/java/io/seata/server/ParameterParser.java]: Abnormal description

Comment (slievrly) [reply server/src/main/java/io/seata/server/ParameterParser.java]: fixed java doc comment

File: server/src/main/java/io/seata/server/ParameterParser.java [hunk 7]
```diff
@@ -23,39 +23,41 @@
...
     private int port = SERVER_DEFAULT_PORT;
     @Parameter(names = {"--storeMode", "-m"}, description = "log store mode : file、db", order = 3)
     private String storeMode = CONFIG.getConfig(ConfigurationKeys.STORE_MODE, SERVER_DEFAULT_STORE_MODE);
     @Parameter(names = {"--serverNode", "-n"}, description = "server node id, such as 1, 2, 3. default is 1", order = 4)
     private int serverNode = SERVER_DEFAULT_NODE;
 
+    /**
+     * Instantiates a new Parameter parser.
+     *
+     * @param args the args
```
Comment (zjinlei) [inline server/src/main/java/io/seata/server/ParameterParser.java]: Abnormal description

Comment (slievrly) [reply server/src/main/java/io/seata/server/ParameterParser.java]: The first args is the name of the parameter, and the second args is the explanation of the parameter.
