### PR TITLE
bugfix: DeleteExecutor. buildBeforeImageSQL keyword checker by db type

### LINKED ISSUE #1754: DeleteExecutor.buildBeforeImageSQL keyword checker not distinguish database
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
DeleteExecutor.buildBeforeImageSQL keyword not distinguish database
image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```

```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by jsbxyyx**
### Ⅰ. Describe what this PR did
keyword checker not distinguish db type

### Ⅱ. Does this pull request fix one issue?

fixes #1754

### CODE REVIEW

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/DeleteExecutor.java [hunk 1]
```diff
@@ -63,7 +62,7 @@ protected TableRecords beforeImage() throws SQLException {
     }
 
     private String buildBeforeImageSQL(SQLDeleteRecognizer visitor, TableMeta tableMeta, ArrayList<List<Object>> paramAppenderList) {
-        KeywordChecker keywordChecker = KeywordCheckerFactory.getKeywordChecker(JdbcConstants.MYSQL);
+        KeywordChecker keywordChecker = KeywordCheckerFactory.getKeywordChecker(getDbType());
         String whereCondition = buildWhereCondition(visitor, paramAppenderList);
         StringBuilder suffix = new StringBuilder(" FROM " + keywordChecker.checkAndReplace(getFromTableInSQL()));
```
Comment (zjinlei) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/DeleteExecutor.java]: getFromTableInSQL() no need to deal with keyworkChecker
