### PR TITLE
optimize check style

### LINKED ISSUE #1055: Optimize check style
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Optimize check style

### Ⅱ. Describe what happened

 
image

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by slievrly**
### Ⅰ. Describe what this PR did

Optimize check style

### Ⅱ. Does this pull request fix one issue?
fix #1055

### CODE REVIEW

File: common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java [hunk 1]
```diff
@@ -115,11 +114,12 @@
      * @return the s
      * @throws EnhancedServiceNotFoundException the enhanced service not found exception
      */
-    public static <S> S load(Class<S> service, String activateName, Object[] args) throws EnhancedServiceNotFoundException {
+    public static <S> S load(Class<S> service, String activateName, Object[] args)
+        throws EnhancedServiceNotFoundException {
```
Comment (lovepoem) [inline common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java]: Why change the line here ？
I think we should have more characters on each line to avoid more line breaks.

File: common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java [hunk 2]
```diff
@@ -137,7 +137,8 @@
      * @return the s
      * @throws EnhancedServiceNotFoundException the enhanced service not found exception
      */
-    public static <S> S load(Class<S> service, String activateName, Class[] argsType, Object[] args) throws EnhancedServiceNotFoundException {
+    public static <S> S load(Class<S> service, String activateName, Class[] argsType, Object[] args)
```
Comment (lovepoem) [inline common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java]: Why change the line here ？
I think we should have more characters on each line to avoid more line breaks.

File: common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java [hunk 3]
```diff
@@ -193,8 +194,9 @@
         return loadFile(service, activateName, loader, null, null);
     }
 
-        @SuppressWarnings("rawtypes")
-    private static <S> S loadFile(Class<S> service, String activateName, ClassLoader loader, Class[] argTypes, Object[] args) {
+    @SuppressWarnings("rawtypes")
+    private static <S> S loadFile(Class<S> service, String activateName, ClassLoader loader, Class[] argTypes,
```
Comment (lovepoem) [inline common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java]: Why change the line here ？
I think we should have more characters on each line to avoid more line breaks.

File: common/src/main/java/io/seata/common/util/ReflectionUtil.java [hunk 4]
```diff
@@ -41,40 +41,41 @@
...
      * @param fieldName the field name
      * @return field value
      * @throws NoSuchFieldException the no such field exception
      * @throws SecurityException the security exception
      * @throws IllegalArgumentException the illegal argument exception
      * @throws IllegalAccessException the illegal access exception
      */
-    public static Object getFieldValue (Object target, String fieldName) throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
+    public static Object getFieldValue(Object target, String fieldName)
+        throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
```
Comment (lovepoem) [inline common/src/main/java/io/seata/common/util/ReflectionUtil.java]: Why change the line here ？
I think we should have more characters on each line to avoid more line breaks.

File: common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java (hunk 2 above)
Comment (slievrly) [reply common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java]: hard wrap at 120 cols
image

**Comment by xingfudeshi** [comment]
@slievrly There are conflicting files.

**Comment by slievrly** [comment]
> @slievrly There are conflicting files.

resolved
