### PR TITLE
bugfix: mysql can not get primary key value

### LINKED ISSUE #1736: insert sql can not getGeneratedKeys
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
insert sql can not rs.getGeneratedKeys()

because genKeys.getGeneratedKeys() operation in InsertExecutor, cause the rs cursor move to last.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by jsbxyyx**
### Ⅰ. Describe what this PR did
fix insert sql not get primary key, **only mysql**.

### Ⅱ. Does this pull request fix one issue?

fixes #1736

### CODE REVIEW

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/InsertExecutor.java [hunk 1]
```diff
@@ -306,6 +306,11 @@ private boolean checkPkValues(List<Object> pkValues) {
             Object v = genKeys.getObject(1);
             pkValues.add(v);
         }
+        try {
+            genKeys.beforeFirst();
+        } catch (SQLException e) {
+            LOGGER.warn("Fail to reset ResultSet cursor. can not get primary key value");
```
Comment (xingfudeshi) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/InsertExecutor.java]: This execption should be ignore?

Comment (jsbxyyx) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/InsertExecutor.java]: only user not need get primary key, can be ignore exception.
